import test from'node:test';import assert from'node:assert/strict';import{evaluatePaExpungement}from'../src/core/record-relief/pennsylvania-expungement.ts';import type{Charge}from'../src/core/record-relief/jurisdiction-engine.ts';const c=(x:Partial<Charge>={}):Charge=>({id:'pa',offenseName:'x',degree:'misdemeanor',disposition:'conviction',...x});
test('PA pardon automatic expungement process',()=>assert.equal(evaluatePaExpungement(c(),{today:'2026-10-07',unconditionalPardon:true}).outcome,'automatic_relief_may_apply'));
test('PA complete acquittal automatic branch',()=>assert.equal(evaluatePaExpungement(c({disposition:'acquittal'}),{today:'2026-10-07',allSameEpisodeChargesAcquitted:true}).outcome,'automatic_relief_may_apply'));
test('PA partial acquittal not automatic',()=>assert.equal(evaluatePaExpungement(c({disposition:'acquittal'}),{today:'2026-10-07',allSameEpisodeChargesAcquitted:false}).outcome,'legal_review_recommended'));
test('PA summary expungement five-year arrest/prosecution-free rule',()=>assert.equal(evaluatePaExpungement(c({degree:'minor_misdemeanor'}),{today:'2026-10-07',summaryConvictionDate:'2020-01-01',freeOfArrestOrProsecutionYears:6}).outcome,'court_or_prosecutor_discretion'));
test('PA age 70 branch ten years after final release',()=>assert.equal(evaluatePaExpungement(c(),{today:'2026-10-07',age:72,finalReleaseDate:'2010-01-01',freeOfArrestOrProsecutionYears:12}).outcome,'court_or_prosecutor_discretion'));
test('PA 6308 branch requires age and sentence completion',()=>assert.equal(evaluatePaExpungement(c(),{today:'2026-10-07',section6308:true,age:21,sentenceComplete:true}).outcome,'likely_eligible_verified'));
test('PA stale no-disposition branch needs certification',()=>assert.equal(evaluatePaExpungement(c({disposition:'arrest_no_charge'}),{today:'2026-10-07',arrestDate:'2024-01-01'}).outcome,'additional_facts_required'));
test('PA prohibited minor-victim ARD branch excluded',()=>assert.equal(evaluatePaExpungement(c(),{today:'2026-10-07',ard:true,victimUnder18:true,ardProhibitedSexualOffense:true}).outcome,'likely_excluded_verified'));
