import test from'node:test';import assert from'node:assert/strict';import{evaluateIndiana}from'../src/core/record-relief/indiana.ts';import{evaluateIndianaSection1}from'../src/core/record-relief/indiana-section1.ts';import type{Charge}from'../src/core/record-relief/jurisdiction-engine.ts';const c:Charge={id:'in',offenseName:'x',degree:'felony',disposition:'conviction'};const b={today:'2026-10-07',pendingCharges:false,newConvictionDuringWait:false,allFinesFeesRestitutionPaid:true,convictionDate:'2010-01-01'};
test('IN section 2 mandatory after conditions',()=>assert.equal(evaluateIndiana({...c,degree:'misdemeanor'},{...b,section:2}).outcome,'likely_eligible_verified'));
test('IN section 3 mandatory after conditions',()=>assert.equal(evaluateIndiana(c,{...b,section:3}).outcome,'likely_eligible_verified'));
test('IN section 4 does not require prosecutor consent after wait',()=>assert.equal(evaluateIndiana(c,{...b,section:4,sentenceCompletionDate:'2015-01-01'}).outcome,'court_or_prosecutor_discretion'));
test('IN section 5 requires written prosecutor consent',()=>assert.equal(evaluateIndiana(c,{...b,section:5,sentenceCompletionDate:'2015-01-01'}).outcome,'court_or_prosecutor_discretion'));
test('IN section 4 clock later of 8 after conviction and 3 after sentence',()=>assert.equal(evaluateIndiana(c,{...b,section:4,sentenceCompletionDate:'2025-01-01'}).eligibilityDate,'2028-01-01'));
test('IN section 5 clock later of 10 after conviction and 5 after sentence',()=>assert.equal(evaluateIndiana(c,{...b,section:5,sentenceCompletionDate:'2025-01-01'}).eligibilityDate,'2030-01-01'));
test('IN automatic dismissal branch',()=>assert.equal(evaluateIndianaSection1({...c,disposition:'dismissal'},'2026-10-07',{allDismissed:true}).outcome,'automatic_relief_may_apply'));
test('IN traditional arrest petition waits one year from arrest/charge',()=>assert.equal(evaluateIndianaSection1({...c,disposition:'arrest_no_charge'},'2026-06-01',{arrestOrChargeDate:'2026-01-01',pendingCharges:false}).eligibilityDate,'2027-01-01'));
