import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame, PageHeader, InlineBadge } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { FastTrackQuote, loadFastTrackQuote } from '@/core/opportunities/opportunity-service';

export default function FastTrackCheckout(){
 const {id}=useLocalSearchParams<{id:string}>();const [quote,setQuote]=useState<FastTrackQuote|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(()=>{if(!id)return;setLoading(true);setError('');loadFastTrackQuote(id).then(setQuote).catch(()=>setError('FastTrack pricing could not be loaded.')).finally(()=>setLoading(false))},[id]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 return <ScreenFrame><PageHeader eyebrow="FAIRPATH FASTTRACK" title="FastTrack checkout" backTo={id?'/housing-apply/'+id:'/housing-applications'}/><ScrollView contentContainerStyle={s.content}>
  {loading?<Text style={s.state}>Loading FastTrack price…</Text>:error?<Text style={s.error}>{error}</Text>:quote?<>
   <View style={s.hero}><InlineBadge tone="lime">FASTTRACK</InlineBadge><Text style={s.price}>{'$'+(quote.amount_due_cents/100).toFixed(2)}</Text><Text style={s.sub}>ONE APPLICATION</Text></View>
   <View style={s.breakdown}><Row label="FastTrack application" value={'$'+(quote.base_amount_cents/100).toFixed(2)}/><Row label="FairPath+ discount" value={quote.discount_cents?'- $'+(quote.discount_cents/100).toFixed(2):'$0.00'}/><View style={s.total}><Text style={s.totalLabel}>TOTAL DUE</Text><Text style={s.totalValue}>{'$'+(quote.amount_due_cents/100).toFixed(2)}</Text></View></View>
   <View style={s.notice}><Lucide name="shield-check" color={C.lime} size={16}/><Text style={s.noticeText}>FastTrack can speed up reuse and review of your information. It does not guarantee housing approval and does not replace property-specific screening.</Text></View>
   {quote.status==='paid'||quote.status==='waived'?<Pressable style={s.primary} onPress={()=>router.replace(('/housing-apply/'+id) as never)}><Text style={s.primaryText}>PAYMENT COMPLETE · RETURN TO APPLICATION</Text></Pressable>:quote.payment_enforced?<View style={s.pending}><Text style={s.pendingTitle}>PAYMENT PROVIDER CONNECTION REQUIRED</Text><Text style={s.pendingBody}>The server is enforcing payment, but a live payment provider has not been connected to this client yet. Do not launch paid FastTrack until checkout is connected and tested.</Text></View>:<><View style={s.dev}><Text style={s.devTitle}>CHECKOUT CONTRACT READY</Text><Text style={s.devBody}>Payment enforcement is currently OFF, so development applications can be tested end-to-end without charging a card. Before launch, connect the payment provider, test webhooks, then enable enforcement in FairPath Admin.</Text></View><Pressable style={s.secondary} onPress={()=>router.replace(('/housing-apply/'+id) as never)}><Text style={s.secondaryText}>RETURN TO APPLICATION</Text></Pressable></>}
  </>:null}
 </ScrollView></ScreenFrame>
}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>}
const s=StyleSheet.create({content:{padding:L.mobileGutter,paddingBottom:40},state:{color:C.mutedStrong},error:{color:C.danger},hero:{borderBottomWidth:1,borderBottomColor:C.borderStrong,paddingBottom:18},price:{color:C.white,fontFamily:F.black,fontSize:38,marginTop:12},sub:{color:C.muted,fontFamily:F.extraBold,fontSize:7,letterSpacing:1,marginTop:2},breakdown:{marginTop:18},row:{height:42,borderBottomWidth:1,borderBottomColor:C.border,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rowLabel:{color:C.mutedStrong,fontSize:10},rowValue:{color:C.white,fontFamily:F.extraBold,fontSize:10},total:{height:54,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:C.borderStrong},totalLabel:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:.9},totalValue:{color:C.white,fontFamily:F.black,fontSize:22},notice:{borderWidth:1,borderColor:'#526F2B',backgroundColor:'#0F150B',padding:13,marginTop:18,flexDirection:'row',gap:9},noticeText:{color:C.mutedStrong,fontSize:9,lineHeight:14,flex:1},pending:{borderWidth:1,borderColor:C.danger,padding:14,marginTop:18},pendingTitle:{color:C.danger,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8},pendingBody:{color:C.mutedStrong,fontSize:9,lineHeight:14,marginTop:6},dev:{borderWidth:1,borderColor:C.borderStrong,padding:14,marginTop:18},devTitle:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8},devBody:{color:C.mutedStrong,fontSize:9,lineHeight:14,marginTop:6},primary:{minHeight:50,backgroundColor:C.lime,justifyContent:'center',alignItems:'center',marginTop:18,paddingHorizontal:12},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:8,letterSpacing:.7,textAlign:'center'},secondary:{height:46,borderWidth:1,borderColor:C.borderStrong,justifyContent:'center',alignItems:'center',marginTop:10},secondaryText:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:8,letterSpacing:.7}});
