import type{JurisdictionCompleteness}from'./rule-contract';
export type CoverageProgress=JurisdictionCompleteness&{currentLawCoveragePercent:number};
export const BATCH01_COMPLETENESS:readonly CoverageProgress[]=[
{jurisdictionCode:'US-OH',remedies:true,substantiveRules:true,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:false,tests:true,mayCalculate:true,currentLawCoveragePercent:92,verifiedOn:'2026-10-07',notes:['Current core and special pathways executable.','Historical rule versions and complete court-specific filing profiles remain gated.']},
{jurisdictionCode:'US-MD',remedies:true,substantiveRules:true,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:true,tests:true,mayCalculate:true,currentLawCoveragePercent:100,verifiedOn:'2026-10-07',notes:['Current statewide substantive expungement law verified through §§10-103, 10-103.1, 10-105, 10-105.1, 10-110 and 10-112.','§10-110 current misdemeanor/felony catalog, derivative attempt/conspiracy/solicitation, special waits, unit/new-case rules, favorable/PBJ/stet/treatment/pardon/public-order/decriminalized/cannabis/vacatur/release-without-charge branches encoded.','100% means current statewide substantive-law calculation coverage, not every historical law version or every local clerk filing profile.']},
{jurisdictionCode:'US-PA',remedies:true,substantiveRules:false,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:true,tests:true,mayCalculate:false,currentLawCoveragePercent:45,verifiedOn:'2026-10-07',notes:['Limited-access gates executable; full offense/exclusion normalization remains.']},
{jurisdictionCode:'US-MI',remedies:true,substantiveRules:false,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:false,tests:true,mayCalculate:false,currentLawCoveragePercent:45,verifiedOn:'2026-10-07',notes:['Application and automatic timing executable; complete prohibited-offense matrix remains.']},
{jurisdictionCode:'US-IN',remedies:true,substantiveRules:false,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:false,tests:true,mayCalculate:false,currentLawCoveragePercent:45,verifiedOn:'2026-10-07',notes:['Section timing/exclusions scaffold executable; full conviction classification remains.']}
];export function calculationGate(code:string){return BATCH01_COMPLETENESS.find(x=>x.jurisdictionCode===code)?.mayCalculate===true}
