import type{JurisdictionCompleteness}from'./rule-contract';
export type CoverageProgress=JurisdictionCompleteness&{currentLawCoveragePercent:number};
export const BATCH01_COMPLETENESS:readonly CoverageProgress[]=[
{jurisdictionCode:'US-OH',remedies:true,substantiveRules:true,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:false,tests:true,mayCalculate:true,currentLawCoveragePercent:92,verifiedOn:'2026-10-07',notes:['Current core and special pathways executable.','Historical rule versions and complete court-specific filing profiles remain gated.']},
{jurisdictionCode:'US-MD',remedies:true,substantiveRules:true,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:true,tests:true,mayCalculate:true,currentLawCoveragePercent:100,verifiedOn:'2026-10-07',notes:['Current statewide substantive expungement law verified through §§10-103, 10-103.1, 10-105, 10-105.1, 10-110 and 10-112.','§10-110 current misdemeanor/felony catalog, derivative attempt/conspiracy/solicitation, special waits, unit/new-case rules, favorable/PBJ/stet/treatment/pardon/public-order/decriminalized/cannabis/vacatur/release-without-charge branches encoded.','100% means current statewide substantive-law calculation coverage, not every historical law version or every local clerk filing profile.']},
{jurisdictionCode:'US-PA',remedies:true,substantiveRules:true,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:true,tests:true,mayCalculate:true,currentLawCoveragePercent:100,verifiedOn:'2026-10-07',notes:['Current statewide substantive relief coverage includes §9122 expungement, §9122.1 petition limited access, §9122.2 Clean Slate and §9122.3 exceptions.','Expungement and limited-access outcomes remain distinct.','100% means current statewide substantive-law calculation coverage, not every historical version or local clerk filing profile.']},
{jurisdictionCode:'US-MI',remedies:true,substantiveRules:true,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:true,tests:true,mayCalculate:true,currentLawCoveragePercent:100,verifiedOn:'2026-10-07',notes:['Current statewide substantive set-aside coverage includes application, automatic Clean Slate, offense exclusions, first-OWI and trafficking-special classification, transaction aggregation and automatic count caps.','MC 227/court-of-conviction filing and MSP processing requirements are source-backed.','100% means current statewide substantive-law calculation coverage, not every historical version or local court workflow.']},
{jurisdictionCode:'US-IN',remedies:true,substantiveRules:true,historicalVersions:false,courtHierarchy:true,localFilingProfiles:false,forms:true,tests:true,mayCalculate:true,currentLawCoveragePercent:100,verifiedOn:'2026-10-07',notes:['Current statewide substantive coverage includes §1 automatic/petition arrest relief and conviction categories §§2-5, current exclusions, exact category clocks, prosecutor-consent/discretion distinctions and filing effects.','Sections 2/3 sealing and sections 4/5 marked-expunged public-record effects are kept distinct.','100% means current statewide substantive-law calculation coverage, not every historical version or local clerk workflow.']}
];export function calculationGate(code:string){return BATCH01_COMPLETENESS.find(x=>x.jurisdictionCode===code)?.mayCalculate===true}
