import { JURISDICTIONS, routeCase, type CaseBundle } from './jurisdiction-engine.ts';import { RECORD_RELIEF_ENGINE_VERSION,getRuleFreshness } from './shared-engine.ts';
export type AdapterMode='single'|'multi_route'|'legacy_specialized';
export type EngineRegistration={jurisdictionCode:string;module:string;exports:readonly string[];mode:AdapterMode};
const SPECIAL:Record<string,Omit<EngineRegistration,'jurisdictionCode'>>={
'US-OH':{module:'ohio',exports:['evaluateOhio295332'],mode:'legacy_specialized'},'US-MD':{module:'maryland',exports:['evaluateMaryland'],mode:'legacy_specialized'},'US-PA':{module:'pennsylvania',exports:['evaluatePennsylvaniaLimitedAccess','evaluatePaExpungement'],mode:'legacy_specialized'},'US-MI':{module:'michigan',exports:['evaluateMichiganApplication','evaluateMichiganAutomatic'],mode:'legacy_specialized'},'US-MA':{module:'massachusetts',exports:['evaluateMassachusettsSeal','evaluateMassachusettsExpunge'],mode:'multi_route'},'US-MN':{module:'minnesota',exports:['evaluateMinnesotaAutomatic','evaluateMinnesotaPetition'],mode:'multi_route'},'US-NJ':{module:'new-jersey',exports:['evaluateNewJerseyCleanSlate','evaluateNewJerseyEarlyPath'],mode:'multi_route'},'US-NY':{module:'new-york',exports:['evaluateNewYork16059','evaluateNewYork16057'],mode:'multi_route'},'US-FED':{module:'federal',exports:['evaluateFederal'],mode:'multi_route'},'US-DC':{module:'district-columbia',exports:['evaluateDistrictColumbia'],mode:'multi_route'},'US-PR':{module:'puerto-rico',exports:['evaluatePuertoRico'],mode:'multi_route'},'US-VI':{module:'virgin-islands',exports:['evaluateVirginIslands'],mode:'multi_route'},'US-GU':{module:'guam',exports:['evaluateGuam'],mode:'multi_route'},'US-MP':{module:'northern-mariana-islands',exports:['evaluateNorthernMarianaIslands'],mode:'multi_route'},'US-AS':{module:'american-samoa',exports:['evaluateAmericanSamoa'],mode:'multi_route'}};
const SLUG:Record<string,string>={'US-NH':'new-hampshire','US-NC':'north-carolina','US-ND':'north-dakota','US-NM':'new-mexico','US-RI':'rhode-island','US-SC':'south-carolina','US-SD':'south-dakota','US-TN':'tennessee','US-WV':'west-virginia','US-WI':'wisconsin'};
const fn=(name:string)=>'evaluate'+name.split('-').map(x=>x[0].toUpperCase()+x.slice(1)).join('');
export const ENGINE_REGISTRY:Readonly<Record<string,EngineRegistration>>=Object.freeze(Object.fromEntries(JURISDICTIONS.map(j=>{const code=j.code;if(SPECIAL[code])return[code,{jurisdictionCode:code,...SPECIAL[code]}];const slug=SLUG[code]??j.name.toLowerCase().replace(/[^a-z]+/g,'-').replace(/^-|-$/g,'');return[code,{jurisdictionCode:code,module:slug,exports:[fn(slug)],mode:'single' as const}]})));
export type DispatchPlan={ok:boolean;authorityCode:string;engineVersion:string;registration:EngineRegistration|null;freshness:ReturnType<typeof getRuleFreshness>;routing:ReturnType<typeof routeCase>;facts:Record<string,unknown>;issues:string[]};
export function planRecordReliefEvaluation(bundle:CaseBundle,facts:Record<string,unknown>={}):DispatchPlan{const routing=routeCase(bundle),registration=ENGINE_REGISTRY[routing.authorityCode]??null,issues:string[]=[];if(!routing.canEvaluate)issues.push('routing_blocked');if(!registration)issues.push('engine_not_registered');return{ok:issues.length===0,authorityCode:routing.authorityCode,engineVersion:RECORD_RELIEF_ENGINE_VERSION,registration,freshness:getRuleFreshness(routing.authorityCode),routing,facts,issues}}
