import type{Charge}from'./jurisdiction-engine';import type{AuthoritySource,RuleResult}from'./rule-contract';
const S:AuthoritySource={authority:'statute',citation:'18 Pa.C.S. § 9122',url:'https://www.legis.state.pa.us/WU01/LI/LI/CT/HTM/18/00.091.022.000..HTM',effectiveFrom:'2024-06-11',verifiedOn:'2026-10-07'};
const out=(c:Charge,o:RuleResult['outcome'],r:string[],m:string[]=[],e?:string):RuleResult=>({jurisdictionCode:'US-PA',remedy:'expungement',outcome:o,reasons:r,missingFacts:m,source:S,chargeIds:[c.id],courtSpecificFilingReady:false,eligibilityDate:e});
const plus=(x:string,n:number)=>{const d=new Date(x+'T00:00:00Z');d.setUTCFullYear(d.getUTCFullYear()+n);return d.toISOString().slice(0,10)};
export type PaExpungementFacts={today:string;arrestDate?:string;noDispositionAndNoActionPending?:boolean;unconditionalPardon?:boolean;age?:number;section6308?:boolean;sentenceComplete?:boolean;allSameEpisodeChargesAcquitted?:boolean;summaryConvictionDate?:string;freeOfArrestOrProsecutionYears?:number;finalReleaseDate?:string;ard?:boolean;victimUnder18?:boolean;ardProhibitedSexualOffense?:boolean};
export function evaluatePaExpungement(c:Charge,f:PaExpungementFacts):RuleResult{
 if(f.unconditionalPardon)return out(c,'automatic_relief_may_apply',['An unconditional pardon is an expungement ground and current law provides an automatic transmission/order process; completion should be verified.']);
 if(c.disposition==='acquittal'){if(f.allSameEpisodeChargesAcquitted===undefined)return out(c,'additional_facts_required',[],['whether all charges from the same conduct/criminal episode ended in acquittal']);return f.allSameEpisodeChargesAcquitted?out(c,'automatic_relief_may_apply',['A complete acquittal is subject to automatic expungement with Commonwealth notice/objection procedure.']):out(c,'legal_review_recommended',['Partial acquittals are excluded from the automatic-acquittal branch.'])}
 if(f.ard&&f.victimUnder18&&f.ardProhibitedSexualOffense)return out(c,'likely_excluded_verified',['§ 9122(b.1) prohibits expungement of this ARD arrest record on the supplied victim/offense facts.']);
 if(c.degree==='minor_misdemeanor'&&c.disposition==='conviction'){if(!f.summaryConvictionDate||f.freeOfArrestOrProsecutionYears===undefined)return out(c,'additional_facts_required',[],['summary conviction date','years free of arrest or prosecution']);const e=plus(f.summaryConvictionDate,5);return out(c,f.freeOfArrestOrProsecutionYears>=5?'court_or_prosecutor_discretion':'waiting_period',['Summary-conviction expungement requires five years free of arrest or prosecution after conviction.'],[],e)}
 if(f.age!==undefined&&f.age>=70){if(!f.finalReleaseDate||f.freeOfArrestOrProsecutionYears===undefined)return out(c,'additional_facts_required',[],['final release from confinement/supervision','years free of arrest or prosecution']);const e=plus(f.finalReleaseDate,10);return out(c,f.freeOfArrestOrProsecutionYears>=10?'court_or_prosecutor_discretion':'waiting_period',['Age-70 expungement requires ten years free of arrest or prosecution after final release.'],[],e)}
 if(f.section6308){if(f.age===undefined||f.sentenceComplete===undefined)return out(c,'additional_facts_required',[],['age','completion of every sentence condition']);return f.age>=21&&f.sentenceComplete?out(c,'likely_eligible_verified',['The supplied §6308 facts satisfy the statutory expungement prerequisites.']):out(c,'waiting_period',['§6308 requires age 21 and completion of all sentence conditions.'])}
 if(c.disposition==='arrest_no_charge'&&f.arrestDate){const e=new Date(f.arrestDate+'T00:00:00Z');e.setUTCMonth(e.getUTCMonth()+18);const ds=e.toISOString().slice(0,10);if(f.today<ds)return out(c,'waiting_period',['The no-disposition repository branch requires 18 months after arrest.'],[],ds);if(f.noDispositionAndNoActionPending===undefined)return out(c,'additional_facts_required',[],['court certification that no disposition is available and no action is pending']);return f.noDispositionAndNoActionPending?out(c,'court_or_prosecutor_discretion',['The 18-month no-disposition facts clear the timing gate; court certification and repository authorization are still required.'],[],ds):out(c,'legal_review_recommended',['The required no-disposition/no-pending-action certification is not established.'])}
 if(['dismissal','nolle_prosequi'].includes(c.disposition))return out(c,'court_or_prosecutor_discretion',['Nonconviction data may be expunged by court order; case-specific procedure still applies.']);
 return out(c,'legal_review_recommended',['No verified §9122 expungement branch matches the supplied facts.']);
}
