import type { CaseBundle } from './jurisdiction-engine';
export type ReliefOutcome='likely_eligible_verified'|'waiting_period'|'likely_excluded_verified'|'automatic_relief_may_apply'|'court_or_prosecutor_discretion'|'additional_facts_required'|'rule_not_verified'|'legal_review_recommended';
export type Remedy='sealing'|'expungement'|'set_aside'|'limited_access'|'automatic_clearing'|'pardon'|'certificate'|'vacatur'|'dismissal'|'other';
export type AuthoritySource={authority:'statute'|'court_rule'|'judiciary'|'government';citation:string;url:string;effectiveFrom?:string;effectiveTo?:string;verifiedOn:string};
export type RuleResult={jurisdictionCode:string;remedy:Remedy;outcome:ReliefOutcome;reasons:string[];missingFacts:string[];source:AuthoritySource;chargeIds:string[];eligibilityDate?:string;courtSpecificFilingReady:boolean};
export type RuleVersion={key:string;version:number;jurisdictionCode:string;remedy:Remedy;effectiveFrom:string;effectiveTo?:string;verifiedOn:string;source:AuthoritySource;status:'draft'|'verified'|'superseded'|'retired'};
export type JurisdictionCompleteness={jurisdictionCode:string;remedies:boolean;substantiveRules:boolean;historicalVersions:boolean;courtHierarchy:boolean;localFilingProfiles:boolean;forms:boolean;tests:boolean;mayCalculate:boolean;verifiedOn?:string;notes:string[]};
export function selectRuleVersion(rules:readonly RuleVersion[],onDate:string){return rules.filter(r=>r.status==='verified'&&r.effectiveFrom<=onDate&&(!r.effectiveTo||r.effectiveTo>=onDate)).sort((a,b)=>b.version-a.version)[0]??null}
export function fallbackResult(bundle:CaseBundle,today:string):RuleResult[]{return bundle.charges.map(c=>({jurisdictionCode:bundle.venue.jurisdictionCode,remedy:'other',outcome:'rule_not_verified',reasons:['No verified executable rule covers this charge in the current FairPath dataset. This does not mean relief is unavailable.'],missingFacts:[],source:{authority:'government',citation:'FairPath verification gate',url:'',effectiveFrom:today,verifiedOn:today},chargeIds:[c.id],courtSpecificFilingReady:false}))}
