import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput } from 'react-native';
import { notify } from '@/core/ui/notify';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame, PageHeader } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { createHousingInquiry } from '@/core/opportunities/opportunity-service';
export default function HousingInquiry(){const {id}=useLocalSearchParams<{id:string}>();const [subject,setSubject]=useState('Question about this home');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 async function submit(){if(!id||saving)return;if(message.trim().length<10){notify('Add your question','Write at least a short question before sending.');return}setSaving(true);try{await createHousingInquiry({listingId:id,subject,message});notify('Question sent','Your question is in Housing Activity.');router.replace('/housing-activity' as never)}catch(e){if(e instanceof Error&&e.message==='SIGNED_OUT'){router.push(('/sign-up?returnTo='+encodeURIComponent('/housing-inquiry/'+id)) as never);return}notify('Could not send question','Please try again.')}finally{setSaving(false)}}
 return <ScreenFrame><PageHeader eyebrow="FAIRPATH HOUSING" title="Ask about this home" backTo={id?'/housing/'+id:'/find-housing'}/><ScrollView contentContainerStyle={s.content}><Text style={s.intro}>Ask about availability, screening, move-in requirements, utilities, accessibility, or another property-specific detail.</Text><Text style={s.label}>SUBJECT</Text><TextInput style={s.input} value={subject} onChangeText={setSubject} placeholderTextColor={C.muted}/><Text style={s.label}>MESSAGE</Text><TextInput style={[s.input,s.multi]} value={message} onChangeText={setMessage} multiline placeholder="What would you like to know?" placeholderTextColor={C.muted}/><Text style={s.helper}>Do not send Social Security numbers, bank credentials, or other unnecessary sensitive information in messages.</Text><Pressable style={s.primary} onPress={()=>void submit()} disabled={saving}><Text style={s.primaryText}>{saving?'SENDING…':'SEND QUESTION'}</Text><Lucide name="send" color={C.black} size={15}/></Pressable></ScrollView></ScreenFrame>}
const s=StyleSheet.create({content:{padding:L.mobileGutter,paddingBottom:40},intro:{color:C.mutedStrong,fontSize:11,lineHeight:17,marginBottom:18},label:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1,marginTop:12,marginBottom:7},input:{minHeight:48,borderWidth:1,borderColor:C.borderStrong,color:C.white,paddingHorizontal:12,fontSize:13},multi:{minHeight:130,paddingTop:12,textAlignVertical:'top'},helper:{color:C.muted,fontSize:9,lineHeight:14,marginTop:8},primary:{height:50,backgroundColor:C.lime,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:14,marginTop:18},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:9,letterSpacing:.8}});
