import { router, useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { Alert,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame,PageHeader,InlineBadge } from '@/components/ProductChrome';
import { FairPathColors as C,FairPathFonts as F,FairPathLayout as L } from '@/constants/fairpath';
import { HousingApplicationDetail,loadMyHousingApplicationDetail,withdrawMyHousingApplication } from '@/core/opportunities/opportunity-service';
const LABEL:Record<string,string>={started:'IN PROGRESS',submitted:'SUBMITTED',reviewing:'UNDER REVIEW',tour:'TOUR',approved:'APPROVED',denied:'NOT APPROVED',withdrawn:'WITHDRAWN'};
export default function HousingApplication(){const {id}=useLocalSearchParams<{id:string}>();const [item,setItem]=useState<HousingApplicationDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
useEffect(()=>{if(!id)return;loadMyHousingApplicationDetail(id).then(setItem).catch(e=>{if(e instanceof Error&&e.message==='SIGNED_OUT'){router.replace(('/sign-up?returnTo='+encodeURIComponent('/housing-application/'+id)) as never);return}setError('Application could not be loaded.')}).finally(()=>setLoading(false))},[id]);
if(loading)return <ScreenFrame><PageHeader eyebrow="FAIRPATH HOUSING" title="Application" backTo="/housing-applications"/><State text="Loading application…"/></ScreenFrame>;
if(error||!item)return <ScreenFrame><PageHeader eyebrow="FAIRPATH HOUSING" title="Application" backTo="/housing-applications"/><State text={error||'Application not found.'}/></ScreenFrame>;
const fast=item.application_type==='fasttrack';const active=item.status==='started';
const withdraw=()=>Alert.alert('Withdraw application?','This removes the application from your active workflow. It does not contact or withdraw anything from a property owner because this application has not been submitted through FairPath.',[{text:'Cancel',style:'cancel'},{text:'Withdraw',style:'destructive',onPress:async()=>{try{await withdrawMyHousingApplication(item.id);setItem({...item,status:'withdrawn',updated_at:new Date().toISOString()})}catch{Alert.alert('Could not withdraw','Please try again.')}}}]);
return <ScreenFrame><PageHeader eyebrow="FAIRPATH HOUSING" title="Application" backTo="/housing-applications"/><ScrollView contentContainerStyle={s.content}>
<View style={s.statusRow}><InlineBadge tone={fast?'lime':undefined}>{fast?'FASTTRACK':'STANDARD'}</InlineBadge><Text style={s.status}>{LABEL[item.status]??item.status.toUpperCase()}</Text></View>
<Text style={s.title}>{item.listing?.title??'Housing application'}</Text>{item.listing?<><Text style={s.price}>{'$'+Number(item.listing.rent_monthly).toLocaleString()+' / month'}</Text><Text style={s.meta}>{[item.listing.bedrooms!=null?item.listing.bedrooms+' bd':null,item.listing.bathrooms!=null?item.listing.bathrooms+' ba':null,item.listing.city+', '+item.listing.state].filter(Boolean).join(' · ')}</Text></>:null}
<View style={s.notice}><Lucide name="shield-check" color={C.lime} size={16}/><Text style={s.noticeText}>{active?'Nothing has been submitted or charged. This is your private application workspace until you review and confirm the final application.':'This workspace reflects the current FairPath application status.'}</Text></View>
<Text style={s.section}>APPLICATION READINESS</Text><Check title="Identity & contact" body="Keep your name, phone, email and current address ready for the application."/><Check title="Income & employment" body="Prepare current income and employment details. Verification will be requested only when the property workflow requires it."/><Check title="Housing history" body="Prepare current and prior housing information and references."/><Check title="Documents" body="Have supporting documents ready before final review. FairPath will not mark documents verified until verification exists."/>
{fast?<View style={s.fast}><Text style={s.fastTag}>FASTTRACK</Text><Text style={s.fastTitle}>Faster path, same final control.</Text><Text style={s.fastBody}>FastTrack can reuse confirmed FairPath information and organize required items. It does not guarantee approval, submit automatically, or charge you without a separate confirmation.</Text></View>:null}
{item.listing?<Pressable style={s.primary} onPress={()=>router.push(('/housing/'+item.listing!.id) as never)}><Text style={s.primaryText}>VIEW HOME</Text><Lucide name="arrow-right" color={C.black} size={16}/></Pressable>:null}
{active?<Pressable style={s.secondary} onPress={withdraw}><Text style={s.secondaryText}>WITHDRAW FROM WORKSPACE</Text></Pressable>:null}
<Text style={s.updated}>LAST UPDATED {new Date(item.updated_at).toLocaleString()}</Text></ScrollView></ScreenFrame>}
function Check({title,body}:{title:string;body:string}){return <View style={s.check}><View style={s.checkIcon}><Lucide name="circle" color={C.mutedStrong} size={13}/></View><View style={{flex:1}}><Text style={s.checkTitle}>{title}</Text><Text style={s.checkBody}>{body}</Text></View></View>}
function State({text}:{text:string}){return <View style={s.state}><Text style={s.stateText}>{text}</Text></View>}
const s=StyleSheet.create({content:{paddingHorizontal:L.mobileGutter,paddingTop:18,paddingBottom:40},state:{padding:L.mobileGutter},stateText:{color:C.mutedStrong},statusRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},status:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8},title:{color:C.white,fontFamily:F.black,fontSize:26,lineHeight:29,marginTop:14},price:{color:C.white,fontFamily:F.extraBold,fontSize:14,marginTop:8},meta:{color:C.mutedStrong,fontSize:10,marginTop:5},notice:{flexDirection:'row',gap:10,borderWidth:1,borderColor:'#526F2B',backgroundColor:'#0F150B',padding:14,marginTop:18},noticeText:{flex:1,color:C.mutedStrong,fontSize:10,lineHeight:16},section:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.2,marginTop:24,marginBottom:6},check:{flexDirection:'row',gap:10,paddingVertical:14,borderBottomWidth:1,borderBottomColor:C.border},checkIcon:{width:22,paddingTop:2},checkTitle:{color:C.white,fontFamily:F.extraBold,fontSize:12},checkBody:{color:C.mutedStrong,fontSize:10,lineHeight:15,marginTop:4},fast:{borderWidth:1,borderColor:C.borderStrong,padding:15,marginTop:20},fastTag:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.1},fastTitle:{color:C.white,fontFamily:F.black,fontSize:18,marginTop:5},fastBody:{color:C.mutedStrong,fontSize:10,lineHeight:16,marginTop:6},primary:{height:50,backgroundColor:C.lime,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:14,marginTop:20},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:9,letterSpacing:.9},secondary:{height:46,borderWidth:1,borderColor:C.borderStrong,alignItems:'center',justifyContent:'center',marginTop:9},secondaryText:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8},updated:{color:C.muted,fontFamily:F.extraBold,fontSize:7,letterSpacing:.7,marginTop:18}});