import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { notify } from '@/core/ui/notify';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame, PageHeader, InlineBadge } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { MarketplaceClaimEvent, MarketplaceClaimReceipt, MarketplaceMessage, cancelMarketplaceClaim, loadMarketplaceClaimEvents, loadMarketplaceClaimReceipt, loadMarketplaceMessages } from '@/core/marketplace/marketplace-service';

const LABEL:Record<string,string>={requested:'REQUESTED',approved:'APPROVED',ready:'READY FOR PICKUP',picked_up:'PICKED UP',cancelled:'CANCELLED',expired:'EXPIRED',declined:'NOT SELECTED',no_show:'NO-SHOW'};
export default function MarketplaceClaimDetail(){
 const {id}=useLocalSearchParams<{id:string}>();const [claim,setClaim]=useState<MarketplaceClaimReceipt|null>(null);const [events,setEvents]=useState<MarketplaceClaimEvent[]>([]);const [messages,setMessages]=useState<MarketplaceMessage[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(()=>{if(!id)return;setLoading(true);setError('');Promise.all([loadMarketplaceClaimReceipt(id),loadMarketplaceClaimEvents(id),loadMarketplaceMessages(id).catch(()=>[])]).then(([a,b,c])=>{setClaim(a);setEvents(b);setMessages(c)}).catch(e=>setError(e?.message==='SIGNED_OUT'?'Sign in to open your claim.':'Claim could not be loaded.')).finally(()=>setLoading(false))},[id]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 async function cancel(){if(!id)return;notify('Cancel claim?','If you cancel before selection, it will not count against your monthly limit. Cancelling after approval still counts because the item was reserved for you.',[{text:'Keep claim',style:'cancel'},{text:'Cancel claim',style:'destructive',onPress:async()=>{try{await cancelMarketplaceClaim(id);await load()}catch{notify('Could not cancel','Please try again.')}}}])}

 return <ScreenFrame><PageHeader eyebrow="FAIRPATH MARKETPLACE" title="Claim" backTo="/marketplace-claims"/><ScrollView contentContainerStyle={s.content}>
  {loading?<Text style={s.state}>Loading claim…</Text>:error?<Text style={s.error}>{error}</Text>:claim?<><View style={s.head}><InlineBadge tone={['approved','ready'].includes(claim.status)?'lime':undefined}>{LABEL[claim.status]??claim.status.toUpperCase()}</InlineBadge><Text style={s.title}>{claim.item_title}</Text><Text style={s.meta}>{claim.item_city}, {claim.item_state}</Text></View>
   {['approved','ready','picked_up'].includes(claim.status)?<View style={s.pickup}><Text style={s.sectionLabel}>PRIVATE PICKUP</Text>{claim.pickup_deadline&&claim.status!=='picked_up'?<Text style={s.deadline}>PICK UP BY · {new Date(claim.pickup_deadline).toLocaleString()}</Text>:null}<Text style={s.pickupTitle}>{claim.location_name||[claim.address_line1,claim.city,claim.state].filter(Boolean).join(', ')||'Pickup details pending'}</Text>{claim.address_line1?<Text style={s.pickupBody}>{[claim.address_line1,claim.address_line2,claim.city,claim.state,claim.postal_code].filter(Boolean).join(', ')}</Text>:null}{claim.instructions?<Text style={s.pickupBody}>{claim.instructions}</Text>:null}{claim.contact_phone?<Text style={s.pickupBody}>Contact: {claim.contact_phone}</Text>:null}{claim.pickup_code?<View style={s.codeBox}><Text style={s.codeLabel}>YOUR PICKUP CODE</Text><Text style={s.code}>{claim.pickup_code}</Text><Text style={s.codeHelp}>Show this code to the donor at pickup. They enter it in FairPath to complete the handoff.</Text></View>:null}</View>:<View style={s.wait}><Lucide name="eye-off" color={C.lime} size={17}/><View style={{flex:1}}><Text style={s.waitTitle}>{claim.status==='requested'?'ANONYMOUS SELECTION IN PROGRESS':'PICKUP DETAILS LOCKED'}</Text><Text style={s.waitBody}>{claim.status==='requested'?'The donor sees your anonymous claim ID—not your name, race, or profile photo.':'Private pickup details are only available for approved claims.'}</Text></View></View>}

   {events.length?<View style={s.section}><Text style={s.sectionLabel}>ACTIVITY</Text>{events.map(e=><View key={e.id} style={s.event}><View style={s.dot}/><View><Text style={s.eventTitle}>{e.event_type.replaceAll('_',' ').toUpperCase()}</Text><Text style={s.eventDate}>{new Date(e.created_at).toLocaleString()}</Text></View></View>)}</View>:null}

   {['approved','ready'].includes(claim.status)?<View style={s.section}><Text style={s.sectionLabel}>PICKUP MESSAGES FROM DONOR</Text>{messages.length===0?<Text style={s.noMessages}>No pickup message yet. Claimants do not message donors through FairPath before or after selection; the donor sends pickup logistics here when needed.</Text>:messages.map(m=><View key={m.id} style={s.msg}><Text style={s.msgBody}>{m.body}</Text><Text style={s.msgDate}>{new Date(m.created_at).toLocaleString()}</Text></View>)}</View>:null}

   {['requested','approved','ready'].includes(claim.status)?<Pressable style={s.cancel} onPress={()=>void cancel()}><Text style={s.cancelText}>CANCEL CLAIM</Text></Pressable>:null}
   <Pressable style={s.itemLink} onPress={()=>router.push(('/market-item/'+claim.item_id) as never)}><Text style={s.itemLinkText}>VIEW ITEM</Text><Lucide name="arrow-right" color={C.lime} size={14}/></Pressable>
  </>:null}
 </ScrollView></ScreenFrame>
}
const s=StyleSheet.create({content:{padding:L.mobileGutter,paddingBottom:40},state:{color:C.mutedStrong},error:{color:C.danger},head:{paddingBottom:16,borderBottomWidth:1,borderBottomColor:C.borderStrong},title:{color:C.white,fontFamily:F.black,fontSize:24,marginTop:9},meta:{color:C.mutedStrong,fontSize:9,marginTop:5},pickup:{borderWidth:1,borderColor:'#526F2B',backgroundColor:'#0F150B',padding:14,marginTop:16},sectionLabel:{color:C.lime,fontFamily:F.extraBold,fontSize:7,letterSpacing:1,marginBottom:9},deadline:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:.6},pickupTitle:{color:C.white,fontFamily:F.extraBold,fontSize:15,marginTop:8},pickupBody:{color:C.mutedStrong,fontSize:9,lineHeight:14,marginTop:5},codeBox:{borderTopWidth:1,borderTopColor:'#31401F',marginTop:13,paddingTop:12},codeLabel:{color:C.muted,fontFamily:F.extraBold,fontSize:6.5,letterSpacing:.8},code:{color:C.lime,fontFamily:F.black,fontSize:30,letterSpacing:5,marginTop:4},codeHelp:{color:C.muted,fontSize:8.5,lineHeight:13,marginTop:4},wait:{borderWidth:1,borderColor:C.borderStrong,padding:13,marginTop:16,flexDirection:'row',gap:9},waitTitle:{color:C.lime,fontFamily:F.extraBold,fontSize:7,letterSpacing:.8},waitBody:{color:C.mutedStrong,fontSize:8.5,lineHeight:13,marginTop:4},section:{paddingVertical:17,borderBottomWidth:1,borderBottomColor:C.border},event:{flexDirection:'row',gap:9,minHeight:42,paddingVertical:6},dot:{width:8,height:8,borderRadius:4,backgroundColor:C.lime,marginTop:3},eventTitle:{color:C.white,fontFamily:F.extraBold,fontSize:8},eventDate:{color:C.muted,fontSize:7.5,marginTop:3},noMessages:{color:C.muted,fontSize:9,marginBottom:8},msg:{borderLeftWidth:2,borderLeftColor:C.borderStrong,paddingLeft:9,paddingVertical:7},msgBody:{color:C.white,fontSize:9,lineHeight:14},msgDate:{color:C.muted,fontSize:7,marginTop:3},cancel:{height:42,borderWidth:1,borderColor:C.danger,alignItems:'center',justifyContent:'center',marginTop:17},cancelText:{color:C.danger,fontFamily:F.extraBold,fontSize:7.5,letterSpacing:.8},itemLink:{height:46,borderBottomWidth:1,borderBottomColor:C.borderStrong,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},itemLinkText:{color:C.white,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8}});