import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FairPathColors as C } from '@/constants/fairpath';
import { loadJobs, saveJob, type Job } from '@/core/opportunities/opportunity-service';
export default function FindJobs(){
 const [query,setQuery]=useState(''); const [jobs,setJobs]=useState<Job[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 async function run(value=query){setLoading(true);setError('');try{setJobs(await loadJobs(value));}catch{setError('Jobs could not load. Try again.');}finally{setLoading(false);}}
 useEffect(()=>{run('');},[]);
 return <View style={s.screen}><SafeAreaView style={s.safe}>
 <View style={s.head}><Pressable onPress={()=>router.back()}><Text style={s.back}>←</Text></Pressable><View><Text style={s.kicker}>FAIRPATH JOBS</Text><Text style={s.title}>Work that fits your path.</Text></View></View>
 <View style={s.search}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={()=>run()} placeholder="Job title, company or location" placeholderTextColor="#6D736D" style={s.input}/><Pressable style={s.searchBtn} onPress={()=>run()}><Text style={s.searchText}>Search</Text></Pressable></View>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{['Best match','Remote','Full-time','Part-time','Pay','Experience','Benefits','Background fit'].map(x=><Pressable key={x} style={s.chip}><Text style={s.chipText}>{x}</Text></Pressable>)}</ScrollView>
 <ScrollView contentContainerStyle={s.list}>{loading?<Text style={s.muted}>Finding opportunities…</Text>:error?<Text style={s.error}>{error}</Text>:jobs.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No published jobs yet.</Text><Text style={s.muted}>The marketplace is live. Employer listings will appear here when published.</Text></View>:jobs.map(j=><Pressable key={j.id} style={s.card}>
 <View style={s.cardTop}><View style={s.logo}><Text style={s.logoText}>{j.company_name.slice(0,1)}</Text></View><Pressable onPress={()=>saveJob(j.id)}><Text style={s.save}>♡</Text></Pressable></View>
 <Text style={s.jobTitle}>{j.title}</Text><Text style={s.company}>{j.company_name}</Text><Text style={s.meta}>{[j.location_text,j.workplace_type.replace('_',' '),j.employment_type.replace('_',' ')].filter(Boolean).join(' · ')}</Text>
 {j.pay_min!=null?<Text style={s.pay}>{'$'+j.pay_min+(j.pay_max?'–$'+j.pay_max:'')+' / '+(j.pay_period??'period')}</Text>:null}
 <View style={s.tags}>{j.skills.slice(0,3).map(x=><Text key={x} style={s.tag}>{x}</Text>)}</View><View style={s.match}><Text style={s.matchText}>FAIRPATH MATCH</Text><Text style={s.matchSub}>Compatibility details improve as your FairPath profile becomes more complete.</Text></View><View style={s.apply}><Text style={s.applyText}>View job</Text><Text style={s.applyText}>→</Text></View></Pressable>)}</ScrollView>
 </SafeAreaView></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.black},safe:{flex:1,width:'100%',maxWidth:850,alignSelf:'center'},head:{padding:24,paddingBottom:16,flexDirection:'row',gap:20,alignItems:'center'},back:{color:'#fff',fontSize:24},kicker:{color:C.lime,fontFamily:'LeagueSpartan_800ExtraBold',fontSize:9,letterSpacing:1.8},title:{color:'#fff',fontFamily:'LeagueSpartan_900Black',fontSize:28,marginTop:4},search:{flexDirection:'row',gap:10,paddingHorizontal:24},input:{flex:1,height:54,borderRadius:16,borderWidth:1,borderColor:C.border,backgroundColor:C.card,color:'#fff',paddingHorizontal:16},searchBtn:{backgroundColor:C.lime,borderRadius:16,paddingHorizontal:20,justifyContent:'center'},searchText:{color:C.black,fontFamily:'LeagueSpartan_800ExtraBold'},filters:{gap:8,paddingHorizontal:24,paddingVertical:14},chip:{height:34,borderRadius:18,borderWidth:1,borderColor:C.border,paddingHorizontal:13,justifyContent:'center'},chipText:{color:'#C7CBC7',fontSize:11,fontWeight:'700'},list:{padding:24,paddingTop:8,paddingBottom:70,gap:12},card:{borderRadius:22,borderWidth:1,borderColor:C.border,backgroundColor:C.card,padding:20},cardTop:{flexDirection:'row',justifyContent:'space-between'},logo:{width:42,height:42,borderRadius:12,backgroundColor:'#202620',alignItems:'center',justifyContent:'center'},logoText:{color:C.lime,fontFamily:'LeagueSpartan_900Black',fontSize:18},save:{color:'#fff',fontSize:27},jobTitle:{color:'#fff',fontFamily:'LeagueSpartan_900Black',fontSize:23,marginTop:14},company:{color:'#D6D9D6',fontSize:14,marginTop:5},meta:{color:C.muted,fontSize:12,marginTop:7,textTransform:'capitalize'},pay:{color:'#fff',fontWeight:'800',marginTop:12},tags:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:12},tag:{color:'#C9D1C4',fontSize:10,borderWidth:1,borderColor:'#384037',borderRadius:12,paddingHorizontal:9,paddingVertical:5},match:{backgroundColor:'#101610',borderRadius:14,padding:12,marginTop:15},matchText:{color:C.lime,fontFamily:'LeagueSpartan_800ExtraBold',fontSize:8,letterSpacing:1.2},matchSub:{color:C.muted,fontSize:11,marginTop:4},apply:{height:48,borderRadius:14,backgroundColor:C.lime,marginTop:15,paddingHorizontal:15,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},applyText:{color:C.black,fontFamily:'LeagueSpartan_800ExtraBold'},muted:{color:C.muted,lineHeight:20},error:{color:'#FF8A8A'},empty:{padding:24,borderWidth:1,borderColor:C.border,borderRadius:20},emptyTitle:{color:'#fff',fontFamily:'LeagueSpartan_800ExtraBold',fontSize:18,marginBottom:6}});
