import { router, usePathname } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { FairPathLogo } from '@/components/FairPathLogo';
import { BottomNav } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L, FairPathRadius as R } from '@/constants/fairpath';
import { loadFairPathReadiness } from '@/core/profile/profile-service';
import { loadJobs, saveJob, type Job } from '@/core/opportunities/opportunity-service';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DEMO_MEDIA } from '@/core/demo/demo-media';

export default function Home(){
 const pathname=usePathname(); const [readiness,setReadiness]=useState<number|null>(null); const [search,setSearch]=useState(''); const [featured,setFeatured]=useState<Job[]>([]); const [savedJobs,setSavedJobs]=useState<Record<string,boolean>>({});
 const demoJobs:Job[]=[{id:'demo-warehouse',title:'Warehouse Associate',company_name:'Second Chance Logistics',description:'Demo opportunity',location_text:'Columbus, OH',city:'Columbus',state:'OH',postal_code:null,workplace_type:'onsite',employment_type:'full_time',pay_min:19,pay_max:23,pay_period:'hour',benefits:[],skills:[],requirements:[],background_policy_summary:'Demo second-chance opportunity',eligibility_rules:{second_chance_evidence:'explicit'},application_method:'demo',external_apply_url:null,source_label:'FairPath Demo',source_url:null,featured:true,created_at:new Date().toISOString()},{id:'demo-support',title:'Customer Support Specialist',company_name:'Pathway Services',description:'Demo opportunity',location_text:'Remote',city:null,state:null,postal_code:null,workplace_type:'remote',employment_type:'full_time',pay_min:20,pay_max:25,pay_period:'hour',benefits:[],skills:[],requirements:[],background_policy_summary:'Demo opportunity',eligibility_rules:{second_chance_evidence:'explicit'},application_method:'demo',external_apply_url:null,source_label:'FairPath Demo',source_url:null,featured:true,created_at:new Date().toISOString()}];
 useEffect(()=>{let active=true;loadFairPathReadiness().then(x=>{if(active)setReadiness(x.readiness.overallPercentage)}).catch(()=>{if(active)setReadiness(null)});loadJobs().then(x=>{if(active)setFeatured(x.length?x.slice(0,2):demoJobs)}).catch(()=>{if(active)setFeatured(demoJobs)});return()=>{active=false}},[pathname]);
 return <View style={s.screen}><SafeAreaView style={s.safe}>
  <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
   <View style={s.top}><View style={s.brand}><FairPathLogo width={112}/></View><Pressable accessibilityRole="button" accessibilityLabel="Notifications" style={s.bell} onPress={()=>router.push('/me')}><Text style={s.bellText}>♢</Text><View style={s.bellDot}/></Pressable></View>

   <View style={s.hero}><Text style={s.eyebrow}>YOUR FAIRPATH FORWARD</Text><Text style={s.title}>Opportunity has a <Text style={s.titleAccent}>path.</Text></Text><Text style={s.sub}>Jobs. Housing. Resources. A stronger you.</Text><View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={search} onChangeText={setSearch} returnKeyType="search" onSubmitEditing={()=>{const q=search.trim();router.push((q?'/find-jobs?search='+encodeURIComponent(q):'/find') as never)}} style={s.searchInput} placeholder="What are you looking for?" placeholderTextColor={C.muted}/>{search.length>0?<Pressable accessibilityLabel="Clear search" onPress={()=>setSearch('')}><Text style={s.clearSearch}>×</Text></Pressable>:null}</View><View style={s.quickPills}><Pressable style={[s.pill,s.pillActive]} onPress={()=>router.push('/find-jobs')}><Text style={s.pillActiveText}>Jobs</Text></Pressable><Pressable style={s.pill} onPress={()=>router.push('/find-housing')}><Text style={s.pillText}>Housing</Text></Pressable><Pressable style={s.pill} onPress={()=>router.push('/marketplace')}><Text style={s.pillText}>Marketplace</Text></Pressable><Pressable style={s.pill} onPress={()=>router.push('/resources')}><Text style={s.pillText}>Resources</Text></Pressable></View></View>

   <View style={s.sectionHead}><View><Text style={s.featuredTitle}>Featured Opportunities</Text><Text style={s.featuredSub}>Picked to get you moving</Text></View><Pressable style={s.seeAllButton} onPress={()=>router.push('/find-jobs')}><Text style={s.seeAll}>See all</Text><Text style={s.seeAllArrow}>→</Text></Pressable></View>
   <View style={s.featuredList}>{featured.map((j,index)=>{const saved=!!savedJobs[j.id];return <Pressable key={j.id} style={s.jobCard} onPress={()=>router.push(('/job/'+j.id) as never)}>
    <View style={s.jobThumb}><Image source={{uri:Object.values(DEMO_MEDIA.jobs)[index%Object.values(DEMO_MEDIA.jobs).length]}} style={s.jobThumbImage}/><View style={s.featuredFlag}><Text style={s.featuredFlagText}>FEATURED</Text></View></View>
    <View style={s.jobCopy}><View style={s.jobTopRow}><Text style={s.jobTitle} numberOfLines={1}>{j.title}</Text><Pressable accessibilityLabel={saved?'Saved job':'Save job'} hitSlop={10} style={[s.saveButton,saved&&s.saveButtonActive]} onPress={(e)=>{e.stopPropagation?.();if(j.id.startsWith('demo-')){setSavedJobs(prev=>({...prev,[j.id]:!prev[j.id]}));return;}saveJob(j.id).then(()=>setSavedJobs(prev=>({...prev,[j.id]:true}))).catch(()=>Alert.alert('Sign in required','Sign in to save jobs to your FairPath account.'));}}><Text style={[s.saveGlyph,saved&&s.saveGlyphActive]}>{saved?'♥':'♡'}</Text></Pressable></View>
    <Text style={s.jobCompany}>{j.company_name}</Text><Text style={s.jobMeta}>{j.location_text||[j.city,j.state].filter(Boolean).join(', ')}</Text>
    {j.pay_min!=null?<Text style={s.jobPay}>{'$'+Number(j.pay_min).toLocaleString()+(j.pay_max?' – $'+Number(j.pay_max).toLocaleString():'')+' / '+(j.pay_period||'period')}</Text>:null}
    <View style={s.jobBadges}><Text style={s.jobBadge}>{j.employment_type.replace('_',' ')}</Text>{j.workplace_type?<Text style={s.jobBadge}>{j.workplace_type}</Text>:null}{j.eligibility_rules?.second_chance_evidence==='explicit'?<Text style={[s.jobBadge,s.secondChanceBadge]}>Second Chance</Text>:null}</View></View>
   </Pressable>})}</View>

   <View style={s.showcase}><Text style={s.label}>EXPLORE FAIRPATH</Text><View style={s.showcaseGrid}><Pressable style={s.showcaseCard} onPress={()=>router.push('/record-relief' as never)}><Text style={s.showcaseIcon}>⚖</Text><Text style={s.showcaseTitle}>Record Relief</Text><Text style={s.showcaseBody}>Eligibility, countdowns, forms, filing and legal help.</Text></Pressable><Pressable style={s.showcaseCard} onPress={()=>router.push('/fairpath-filing' as never)}><Text style={s.showcaseIcon}>▤</Text><Text style={s.showcaseTitle}>Forms + Filing</Text><Text style={s.showcaseBody}>Prepare paperwork and see the filing workflow.</Text></Pressable><Pressable style={s.showcaseCard} onPress={()=>router.push('/credit-tools' as never)}><Text style={s.showcaseIcon}>↗</Text><Text style={s.showcaseTitle}>Credit Builder</Text><Text style={s.showcaseBody}>Plans, report review, disputes and education.</Text></Pressable><Pressable style={s.showcaseCard} onPress={()=>router.push('/plus' as never)}><Text style={s.showcaseIcon}>+</Text><Text style={s.showcaseTitle}>FairPath+</Text><Text style={s.showcaseBody}>See the $2 membership experience and benefits.</Text></Pressable></View></View>

   <Pressable style={s.readinessCompact} onPress={()=>router.push('/complete-profile' as never)}><View><Text style={s.label}>FAIRPATH READINESS</Text><Text style={s.readinessCompactTitle}>Complete your profile</Text></View><View style={s.readinessRight}><Text style={s.readinessCompactPct}>{readiness==null?'—':readiness+'%'}</Text><Text style={s.action}>CONTINUE →</Text></View></Pressable>

   <View style={s.ai}>
    <View style={s.aiCopy}><Text style={s.label}>FAIRPATH AI</Text><Text style={s.aiTitle}>Need help with the next move?</Text><Text style={s.aiBody}>Applications, résumés, interview prep, housing questions and your reentry plan.</Text></View>
    <Pressable style={s.aiButton} onPress={()=>router.push('/fairpath-ai')}><Text style={s.aiButtonText}>OPEN AI</Text><Text style={s.aiButtonText}>→</Text></Pressable>
   </View>
  </ScrollView>
  <BottomNav/>
 </SafeAreaView></View>
}
const s=StyleSheet.create({
 screen:{flex:1,backgroundColor:C.black},safe:{flex:1,width:'100%',maxWidth:L.consumerMaxWidth,alignSelf:'center'},content:{paddingHorizontal:L.mobileGutter,paddingTop:8,paddingBottom:88},
 top:{height:62,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},brand:{flexDirection:'row',alignItems:'center'},bell:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.card,alignItems:'center',justifyContent:'center',position:'relative'},bellText:{color:C.white,fontFamily:F.extraBold,fontSize:18,lineHeight:20},bellDot:{position:'absolute',right:6,top:6,width:7,height:7,borderRadius:4,backgroundColor:C.lime,borderWidth:1,borderColor:C.black},
 hero:{paddingBottom:14},eyebrow:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.5,marginBottom:8},title:{color:C.white,fontFamily:F.extraBold,fontSize:36,lineHeight:38,letterSpacing:-1.3,maxWidth:520},titleAccent:{color:C.lime},sub:{color:C.mutedStrong,fontFamily:F.medium,fontSize:12,lineHeight:18,marginTop:9,maxWidth:500},search:{height:50,marginTop:20,borderRadius:25,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.card,flexDirection:'row',alignItems:'center',paddingHorizontal:15},searchIcon:{color:C.lime,fontSize:19,marginRight:9},searchInput:{flex:1,color:C.white,fontFamily:F.medium,fontSize:12,paddingVertical:0},clearSearch:{color:C.mutedStrong,fontSize:20,paddingLeft:10},quickPills:{flexDirection:'row',gap:7,marginTop:11,flexWrap:'wrap'},pill:{height:36,borderRadius:18,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.black,paddingHorizontal:15,alignItems:'center',justifyContent:'center'},pillActive:{backgroundColor:C.lime,borderColor:C.lime},pillText:{color:C.white,fontFamily:F.bold,fontSize:9},pillActiveText:{color:C.black,fontFamily:F.extraBold,fontSize:9},
 readiness:{paddingVertical:18,borderBottomWidth:1,borderBottomColor:C.border},readinessTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},label:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.2},readinessTitle:{color:C.white,fontFamily:F.extraBold,fontSize:18,marginTop:5},percent:{color:C.white,fontFamily:F.black,fontSize:21},
 track:{height:4,backgroundColor:C.border,marginTop:14},fill:{height:'100%',backgroundColor:C.lime},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:11},small:{color:C.muted,fontSize:10},action:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8},
 sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',marginTop:20,marginBottom:11},featuredTitle:{color:C.white,fontFamily:F.extraBold,fontSize:17,letterSpacing:-.3},featuredSub:{color:C.muted,fontFamily:F.medium,fontSize:9,marginTop:2},seeAllButton:{height:28,paddingHorizontal:0,flexDirection:'row',alignItems:'center',gap:5,borderBottomWidth:1,borderBottomColor:C.lime},seeAll:{color:C.lime,fontFamily:F.extraBold,fontSize:9},seeAllArrow:{color:C.lime,fontFamily:F.extraBold,fontSize:11},featuredList:{gap:10},jobCard:{minHeight:116,borderRadius:4,borderWidth:1,borderColor:C.borderStrong,backgroundColor:'#0B0D0B',flexDirection:'row',padding:10,alignItems:'center'},jobThumb:{width:82,height:94,borderRadius:3,backgroundColor:C.surfaceRaised,borderWidth:1,borderColor:C.borderStrong,overflow:'hidden',position:'relative'},jobThumbImage:{width:'100%',height:'100%'},featuredFlag:{position:'absolute',left:0,bottom:0,backgroundColor:C.lime,borderRadius:0,paddingHorizontal:7,paddingVertical:4},featuredFlagText:{color:C.black,fontFamily:F.extraBold,fontSize:6,letterSpacing:.7},jobCopy:{flex:1,minWidth:0,paddingLeft:11},jobTopRow:{flexDirection:'row',alignItems:'center',gap:8},jobTitle:{flex:1,color:C.white,fontFamily:F.extraBold,fontSize:13,letterSpacing:-.2},saveButton:{width:30,height:30,borderRadius:3,borderWidth:1,borderColor:C.borderStrong,alignItems:'center',justifyContent:'center',backgroundColor:C.black},saveButtonActive:{backgroundColor:C.lime,borderColor:C.lime},saveGlyph:{color:C.white,fontSize:17,lineHeight:18},saveGlyphActive:{color:C.black},jobCompany:{color:C.mutedStrong,fontFamily:F.semiBold,fontSize:10,marginTop:3},jobMeta:{color:C.muted,fontFamily:F.regular,fontSize:9,marginTop:3},jobPay:{color:C.white,fontFamily:F.extraBold,fontSize:11,marginTop:4},jobBadges:{flexDirection:'row',gap:5,marginTop:8,flexWrap:'wrap'},jobBadge:{color:C.mutedStrong,fontFamily:F.semiBold,fontSize:7,backgroundColor:'transparent',borderRadius:2,borderWidth:1,borderColor:C.borderStrong,paddingHorizontal:7,paddingVertical:4,textTransform:'capitalize'},secondChanceBadge:{color:C.lime,backgroundColor:'transparent',borderWidth:1,borderColor:'#526F2B'},readinessCompact:{marginTop:14,borderRadius:12,borderWidth:1,borderColor:C.border,backgroundColor:C.card,padding:13,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},readinessCompactTitle:{color:C.white,fontFamily:F.bold,fontSize:13,marginTop:3},readinessRight:{alignItems:'flex-end'},readinessCompactPct:{color:C.lime,fontFamily:F.extraBold,fontSize:14,marginBottom:4},
 showcase:{marginTop:18},showcaseGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:9},showcaseCard:{width:'48.5%',minHeight:118,borderRadius:14,borderWidth:1,borderColor:C.border,backgroundColor:C.card,padding:12},showcaseIcon:{color:C.lime,fontFamily:F.extraBold,fontSize:18},showcaseTitle:{color:C.white,fontFamily:F.bold,fontSize:12,marginTop:8},showcaseBody:{color:C.muted,fontSize:9,lineHeight:14,marginTop:4},ai:{marginTop:12,paddingTop:16,borderTopWidth:1,borderTopColor:C.border,paddingBottom:18},aiCopy:{paddingRight:8},aiTitle:{color:C.white,fontFamily:F.black,fontSize:22,marginTop:6},aiBody:{color:C.muted,fontSize:12,lineHeight:18,marginTop:6},
 aiButton:{height:44,borderRadius:R.sm,backgroundColor:C.lime,paddingHorizontal:13,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:14},aiButtonText:{color:C.black,fontFamily:F.extraBold,fontSize:10,letterSpacing:.7}
});
