import { router, usePathname } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { FairPathLogo } from '@/components/FairPathLogo';
import { Lucide } from '@react-native-vector-icons/lucide';
import { BottomNav } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { loadFairPathReadiness } from '@/core/profile/profile-service';
import { loadJobs, saveJob, type Job } from '@/core/opportunities/opportunity-service';
import { SafeAreaView } from 'react-native-safe-area-context';
import { DEMO_MEDIA } from '@/core/demo/demo-media';

export default function Home(){
 const pathname=usePathname(); const [readiness,setReadiness]=useState<number|null>(null); const [search,setSearch]=useState(''); const [featured,setFeatured]=useState<Job[]>([]); const [savedJobs,setSavedJobs]=useState<Record<string,boolean>>({});
 const demoJobs:Job[]=[{id:'demo-warehouse',title:'Warehouse Associate',company_name:'Second Chance Logistics',description:'Demo opportunity',location_text:'Columbus, OH',city:'Columbus',state:'OH',postal_code:null,workplace_type:'onsite',employment_type:'full_time',pay_min:19,pay_max:23,pay_period:'hour',benefits:[],skills:[],requirements:[],background_policy_summary:'Demo second-chance opportunity',eligibility_rules:{second_chance_evidence:'explicit'},application_method:'demo',external_apply_url:null,source_label:'FairPath Demo',source_url:null,featured:true,created_at:new Date().toISOString()},{id:'demo-support',title:'Customer Support Specialist',company_name:'Pathway Services',description:'Demo opportunity',location_text:'Remote',city:null,state:null,postal_code:null,workplace_type:'remote',employment_type:'full_time',pay_min:20,pay_max:25,pay_period:'hour',benefits:[],skills:[],requirements:[],background_policy_summary:'Demo opportunity',eligibility_rules:{second_chance_evidence:'explicit'},application_method:'demo',external_apply_url:null,source_label:'FairPath Demo',source_url:null,featured:true,created_at:new Date().toISOString()}];
 useEffect(()=>{let active=true;loadFairPathReadiness().then(x=>{if(active)setReadiness(x.readiness.overallPercentage)}).catch(()=>{if(active)setReadiness(null)});loadJobs().then(x=>{if(active)setFeatured(x.length?x.slice(0,2):demoJobs)}).catch(()=>{if(active)setFeatured(demoJobs)});return()=>{active=false}},[pathname]);
 return <View style={s.screen}><SafeAreaView style={s.safe}>
  <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
   <View style={s.top}><View style={s.brand}><FairPathLogo width={112}/></View><Pressable accessibilityRole="button" accessibilityLabel="Notifications" style={s.bell} onPress={()=>router.push('/notifications' as never)}><Lucide name="bell" color={C.white} size={17}/></Pressable></View>

   <View style={s.hero}><Text style={s.eyebrow}>YOUR FAIRPATH FORWARD</Text><Text style={s.title}>Opportunity has a <Text style={s.titleAccent}>path.</Text></Text><Text style={s.sub}>Jobs. Housing. Resources. A stronger you.</Text><View style={s.search}><Lucide name="search" color={C.lime} size={17}/><TextInput value={search} onChangeText={setSearch} returnKeyType="search" onSubmitEditing={()=>{const q=search.trim();router.push((q?'/find-jobs?search='+encodeURIComponent(q):'/find') as never)}} style={s.searchInput} placeholder="Search jobs..." placeholderTextColor={C.muted}/>{search.length>0?<Pressable accessibilityLabel="Clear search" onPress={()=>setSearch('')}><Text style={s.clearSearch}>×</Text></Pressable>:null}</View><View style={s.quickPills}><Pressable style={[s.pill,s.pillActive]} onPress={()=>router.push('/find-jobs')}><Text style={s.pillActiveText}>Jobs</Text></Pressable><Pressable style={s.pill} onPress={()=>router.push('/find-housing')}><Text style={s.pillText}>Housing</Text></Pressable><Pressable style={s.pill} onPress={()=>router.push('/marketplace')}><Text style={s.pillText}>Marketplace</Text></Pressable><Pressable style={s.pill} onPress={()=>router.push('/resources')}><Text style={s.pillText}>Resources</Text></Pressable></View></View>

   <View style={s.sectionHead}><View><Text style={s.featuredTitle}>Featured Opportunities</Text><Text style={s.featuredSub}>Featured across FairPath</Text></View><Pressable style={s.seeAllButton} onPress={()=>router.push('/find-jobs')}><Text style={s.seeAll}>See all</Text><Text style={s.seeAllArrow}>→</Text></Pressable></View>
   <View style={s.featuredList}>{featured.map((j,index)=>{const saved=!!savedJobs[j.id];return <Pressable key={j.id} style={s.jobCard} onPress={()=>router.push(('/job/'+j.id) as never)}>
    <View style={s.jobThumb}><Image source={{uri:Object.values(DEMO_MEDIA.jobs)[index%Object.values(DEMO_MEDIA.jobs).length]}} style={s.jobThumbImage}/><View style={s.featuredFlag}><Text style={s.featuredFlagText}>FEATURED</Text></View></View>
    <View style={s.jobCopy}><View style={s.jobTopRow}><Text style={s.jobTitle} numberOfLines={1}>{j.title}</Text><Pressable accessibilityLabel={saved?'Saved job':'Save job'} hitSlop={10} style={[s.saveButton,saved&&s.saveButtonActive]} onPress={(e)=>{e.stopPropagation?.();if(j.id.startsWith('demo-')){setSavedJobs(prev=>({...prev,[j.id]:!prev[j.id]}));return;}saveJob(j.id).then(()=>setSavedJobs(prev=>({...prev,[j.id]:true}))).catch(()=>Alert.alert('Sign in required','Sign in to save jobs to your FairPath account.'));}}><Lucide name={saved?'bookmark-check':'bookmark'} color={saved?C.black:C.white} size={15}/></Pressable></View>
    <Text style={s.jobCompany}>{j.company_name}</Text><Text style={s.jobMeta}>{j.location_text||[j.city,j.state].filter(Boolean).join(', ')}</Text>
    {j.pay_min!=null?<Text style={s.jobPay}>{'$'+Number(j.pay_min).toLocaleString()+(j.pay_max?' – $'+Number(j.pay_max).toLocaleString():'')+' / '+(j.pay_period||'period')}</Text>:null}
    <View style={s.jobBadges}><Text style={s.jobBadge}>{j.employment_type.replace('_',' ')}</Text>{j.workplace_type?<Text style={s.jobBadge}>{j.workplace_type}</Text>:null}{j.eligibility_rules?.second_chance_evidence==='explicit'?<Text style={[s.jobBadge,s.secondChanceBadge]}>Second Chance</Text>:null}</View></View>
   </Pressable>})}</View>

   <View style={s.showcase}><View style={s.showcaseHeader}><View><Text style={s.label}>EXPLORE FAIRPATH</Text><Text style={s.showcaseIntro}>Tools built around your next move.</Text></View><View style={s.showcaseRule}/></View><View style={s.showcaseGrid}>
    <Pressable style={s.showcaseCard} onPress={()=>router.push('/record-relief' as never)}><View style={s.showcaseIconWrap}><Lucide name="scale" color={C.lime} size={18}/></View><View style={s.showcaseCopy}><Text style={s.showcaseTitle}>Record Relief</Text><Text style={s.showcaseBody}>Check possible relief paths and filing steps.</Text></View><Lucide name="arrow-up-right" color={C.mutedStrong} size={15}/></Pressable>
    <Pressable style={s.showcaseCard} onPress={()=>router.push('/fairpath-filing' as never)}><View style={s.showcaseIconWrap}><Lucide name="file-text" color={C.lime} size={18}/></View><View style={s.showcaseCopy}><Text style={s.showcaseTitle}>Forms + Filing</Text><Text style={s.showcaseBody}>Prepare, review and organize official paperwork.</Text></View><Lucide name="arrow-up-right" color={C.mutedStrong} size={15}/></Pressable>
    <Pressable style={s.showcaseCard} onPress={()=>router.push('/credit-tools' as never)}><View style={s.showcaseIconWrap}><Lucide name="trending-up" color={C.lime} size={18}/></View><View style={s.showcaseCopy}><Text style={s.showcaseTitle}>Credit Builder</Text><Text style={s.showcaseBody}>Build a focused plan and track progress.</Text></View><Lucide name="arrow-up-right" color={C.mutedStrong} size={15}/></Pressable>
    <Pressable style={[s.showcaseCard,s.showcasePlus]} onPress={()=>router.push('/plus' as never)}><View style={s.showcaseIconWrap}><Lucide name="crown" color={C.lime} size={18}/></View><View style={s.showcaseCopy}><Text style={s.showcaseTitle}>FairPath+</Text><Text style={s.showcaseBody}>Unlock more automation and guided tools.</Text></View><Lucide name="arrow-up-right" color={C.mutedStrong} size={15}/></Pressable>
   </View></View>

   <Pressable style={s.readinessPanel} onPress={()=>router.push('/complete-profile' as never)}>
    <View style={s.readinessHead}><Text style={s.label}>FAIRPATH READINESS</Text><Text style={s.readinessPct}>{readiness==null?'—':readiness+'%'}</Text></View>
    <View style={s.readinessMain}><View style={s.readinessCopy}><Text style={s.readinessPanelTitle}>{readiness!=null&&readiness>=100?'Profile ready':'Complete your profile'}</Text><Text style={s.readinessPanelBody}>{readiness!=null&&readiness>=100?'Your FairPath profile is up to date.':'Finish your profile to improve matching, autofill and opportunity screening.'}</Text></View><Lucide name="arrow-right" color={C.lime} size={18}/></View>
    <View style={s.readinessTrack}><View style={[s.readinessFill,{width:(readiness??0)+'%'}]}/></View>
   </Pressable>

   <Pressable style={s.aiPanel} onPress={()=>router.push('/fairpath-ai' as never)}>
    <View style={s.aiTop}><View><Text style={s.label}>FAIRPATH AI</Text><Text style={s.aiTitle}>Need help with the next move?</Text></View><View style={s.aiIconWrap}><Lucide name="bot" color={C.lime} size={18}/></View></View>
    <Text style={s.aiBody}>Applications, résumés, interview prep, housing questions and your reentry plan.</Text>
    <View style={s.aiFooter}><View style={s.aiRule}/><View style={s.aiAction}><Text style={s.aiActionText}>OPEN FAIRPATH AI</Text><Lucide name="arrow-right" color={C.lime} size={15}/></View></View>
   </Pressable>
  </ScrollView>
  <BottomNav/>
 </SafeAreaView></View>
}
const s=StyleSheet.create({
 screen:{flex:1,backgroundColor:C.black},safe:{flex:1,width:'100%',maxWidth:L.consumerMaxWidth,alignSelf:'center'},content:{paddingHorizontal:L.mobileGutter,paddingTop:8,paddingBottom:88},
 top:{height:62,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:18},brand:{flexDirection:'row',alignItems:'center'},bell:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.card,alignItems:'center',justifyContent:'center'},
 hero:{paddingBottom:14},eyebrow:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.5,marginBottom:8},title:{color:C.white,fontFamily:F.extraBold,fontSize:36,lineHeight:38,letterSpacing:-1.3,maxWidth:520},titleAccent:{color:C.lime},sub:{color:C.mutedStrong,fontFamily:F.medium,fontSize:12,lineHeight:18,marginTop:9,maxWidth:500},search:{height:50,marginTop:20,borderRadius:25,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.card,flexDirection:'row',alignItems:'center',gap:9,paddingHorizontal:15},searchInput:{flex:1,color:C.white,fontFamily:F.medium,fontSize:12,paddingVertical:0},clearSearch:{color:C.mutedStrong,fontSize:20,paddingLeft:10},quickPills:{flexDirection:'row',gap:7,marginTop:11,flexWrap:'wrap'},pill:{height:36,borderRadius:18,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.black,paddingHorizontal:15,alignItems:'center',justifyContent:'center'},pillActive:{backgroundColor:C.lime,borderColor:C.lime},pillText:{color:C.white,fontFamily:F.bold,fontSize:9},pillActiveText:{color:C.black,fontFamily:F.extraBold,fontSize:9},
 readiness:{paddingVertical:18,borderBottomWidth:1,borderBottomColor:C.border},readinessTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},label:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.2},readinessTitle:{color:C.white,fontFamily:F.extraBold,fontSize:18,marginTop:5},percent:{color:C.white,fontFamily:F.black,fontSize:21},
 track:{height:4,backgroundColor:C.border,marginTop:14},fill:{height:'100%',backgroundColor:C.lime},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:11},small:{color:C.muted,fontSize:10},action:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8},
 sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',marginTop:20,marginBottom:11},featuredTitle:{color:C.white,fontFamily:F.extraBold,fontSize:17,letterSpacing:-.3},featuredSub:{color:C.muted,fontFamily:F.medium,fontSize:9,marginTop:2},seeAllButton:{height:28,paddingHorizontal:0,flexDirection:'row',alignItems:'center',gap:5,borderBottomWidth:1,borderBottomColor:C.lime},seeAll:{color:C.lime,fontFamily:F.extraBold,fontSize:9},seeAllArrow:{color:C.lime,fontFamily:F.extraBold,fontSize:11},featuredList:{gap:10},jobCard:{minHeight:116,borderRadius:4,borderWidth:1,borderColor:C.borderStrong,backgroundColor:'#0B0D0B',flexDirection:'row',padding:10,alignItems:'center'},jobThumb:{width:82,height:94,borderRadius:3,backgroundColor:C.surfaceRaised,borderWidth:1,borderColor:C.borderStrong,overflow:'hidden',position:'relative'},jobThumbImage:{width:'100%',height:'100%'},featuredFlag:{position:'absolute',left:0,bottom:0,backgroundColor:C.lime,borderRadius:0,paddingHorizontal:7,paddingVertical:4},featuredFlagText:{color:C.black,fontFamily:F.extraBold,fontSize:6,letterSpacing:.7},jobCopy:{flex:1,minWidth:0,paddingLeft:11},jobTopRow:{flexDirection:'row',alignItems:'center',gap:8},jobTitle:{flex:1,color:C.white,fontFamily:F.extraBold,fontSize:13,letterSpacing:-.2},saveButton:{width:30,height:30,borderRadius:3,borderWidth:1,borderColor:C.borderStrong,alignItems:'center',justifyContent:'center',backgroundColor:C.black},saveButtonActive:{backgroundColor:C.lime,borderColor:C.lime},jobCompany:{color:C.mutedStrong,fontFamily:F.semiBold,fontSize:10,marginTop:3},jobMeta:{color:C.muted,fontFamily:F.regular,fontSize:9,marginTop:3},jobPay:{color:C.white,fontFamily:F.extraBold,fontSize:11,marginTop:4},jobBadges:{flexDirection:'row',gap:5,marginTop:8,flexWrap:'wrap'},jobBadge:{color:C.mutedStrong,fontFamily:F.semiBold,fontSize:7,backgroundColor:'transparent',borderRadius:2,borderWidth:1,borderColor:C.borderStrong,paddingHorizontal:7,paddingVertical:4,textTransform:'capitalize'},secondChanceBadge:{color:C.lime,backgroundColor:'transparent',borderWidth:1,borderColor:'#526F2B'},readinessPanel:{marginTop:14,borderRadius:0,borderTopWidth:1,borderBottomWidth:1,borderColor:C.borderStrong,backgroundColor:'#0A0C0A',paddingVertical:14,paddingHorizontal:2},readinessHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},readinessPct:{color:C.lime,fontFamily:F.extraBold,fontSize:18,letterSpacing:-.4},readinessMain:{flexDirection:'row',alignItems:'center',marginTop:9},readinessCopy:{flex:1,minWidth:0,paddingRight:14},readinessPanelTitle:{color:C.white,fontFamily:F.extraBold,fontSize:15,letterSpacing:-.2},readinessPanelBody:{color:C.muted,fontFamily:F.regular,fontSize:9,lineHeight:14,marginTop:4,maxWidth:290},readinessTrack:{height:2,backgroundColor:C.border,marginTop:13},readinessFill:{height:'100%',backgroundColor:C.lime},
 showcase:{marginTop:22},showcaseHeader:{flexDirection:'row',alignItems:'flex-end',gap:12},showcaseIntro:{color:C.muted,fontFamily:F.medium,fontSize:9,marginTop:3},showcaseRule:{flex:1,height:1,backgroundColor:C.borderStrong,marginBottom:2},showcaseGrid:{marginTop:10,borderTopWidth:1,borderTopColor:C.borderStrong},showcaseCard:{minHeight:78,borderRadius:0,borderBottomWidth:1,borderBottomColor:C.borderStrong,backgroundColor:'#0A0C0A',paddingHorizontal:10,paddingVertical:11,flexDirection:'row',alignItems:'center'},showcasePlus:{borderLeftWidth:2,borderLeftColor:C.lime},showcaseIconWrap:{width:36,height:36,borderRadius:2,borderWidth:1,borderColor:C.borderStrong,backgroundColor:C.black,alignItems:'center',justifyContent:'center',marginRight:11},showcaseCopy:{flex:1,minWidth:0,paddingRight:10},showcaseTitle:{color:C.white,fontFamily:F.extraBold,fontSize:12,letterSpacing:-.1},showcaseBody:{color:C.muted,fontSize:9,lineHeight:14,marginTop:3},aiPanel:{marginTop:12,paddingTop:16,paddingBottom:18,paddingHorizontal:12,borderTopWidth:1,borderBottomWidth:1,borderLeftWidth:3,borderTopColor:'#31401F',borderBottomColor:C.borderStrong,borderLeftColor:C.lime,backgroundColor:'#10150C'},aiTop:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between'},aiTitle:{color:C.white,fontFamily:F.extraBold,fontSize:22,lineHeight:25,letterSpacing:-.5,marginTop:6,maxWidth:285},aiIconWrap:{width:38,height:38,borderRadius:2,borderWidth:1,borderColor:'#526F2B',backgroundColor:'#16200F',alignItems:'center',justifyContent:'center',marginTop:2},aiBody:{color:C.muted,fontFamily:F.regular,fontSize:10,lineHeight:16,marginTop:8,maxWidth:310},aiFooter:{marginTop:15},aiRule:{height:1,backgroundColor:'#31401F'},aiAction:{height:36,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#131B0E',paddingHorizontal:10,borderLeftWidth:2,borderLeftColor:C.lime},aiActionText:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.1}
});
