import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ScreenFrame, PageHeader, InlineBadge } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { loadMyHousingApplications, MyHousingApplication } from '@/core/opportunities/opportunity-service';
const LABEL:Record<string,string>={started:'IN PROGRESS',submitted:'SUBMITTED',reviewing:'UNDER REVIEW',tour:'TOUR',approved:'APPROVED',denied:'NOT APPROVED',withdrawn:'WITHDRAWN'};
export default function HousingApplications(){const [rows,setRows]=useState<MyHousingApplication[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{loadMyHousingApplications().then(setRows).catch(e=>setError(e?.message==='SIGNED_OUT'?'Sign in to see your housing applications.':'Applications could not be loaded.')).finally(()=>setLoading(false))},[]);return <ScreenFrame><PageHeader eyebrow="FAIRPATH HOUSING" title="Applications" backTo="/me"/><ScrollView contentContainerStyle={s.content}><Text style={s.intro}>Track every housing application from start through a final decision.</Text>{loading?<State text="Loading applications…"/>:error?<State text={error}/>:rows.length===0?<View style={s.empty}><Text style={s.emptyTitle}>NO HOUSING APPLICATIONS</Text><Text style={s.emptyBody}>When you start a standard or FastTrack application, it will appear here.</Text><Pressable style={s.action} onPress={()=>router.push('/find-housing' as never)}><Text style={s.actionText}>FIND HOUSING</Text></Pressable></View>:rows.map(a=><Pressable key={a.id} style={s.card} onPress={()=>router.push(('/housing-application/'+a.id) as never)}><View style={s.top}><InlineBadge tone={a.application_type==='fasttrack'?'lime':undefined}>{a.application_type==='fasttrack'?'FASTTRACK':'STANDARD'}</InlineBadge><Text style={s.status}>{LABEL[a.status]??a.status.toUpperCase()}</Text></View><Text style={s.title}>{a.listing?.title??'Housing application'}</Text>{a.listing?<><Text style={s.price}>{'$'+Number(a.listing.rent_monthly).toLocaleString()+' / month'}</Text><Text style={s.location}>{a.listing.city}, {a.listing.state}</Text></>:null}<Text style={s.updated}>UPDATED {new Date(a.updated_at).toLocaleDateString()}</Text></Pressable>)}</ScrollView></ScreenFrame>}
function State({text}:{text:string}){return <View style={s.state}><Text style={s.stateText}>{text}</Text></View>}
const s=StyleSheet.create({content:{paddingHorizontal:L.mobileGutter,paddingBottom:36},intro:{color:C.mutedStrong,fontSize:12,lineHeight:18,paddingVertical:16,borderBottomWidth:1,borderBottomColor:C.border},state:{paddingVertical:40,alignItems:'center'},stateText:{color:C.mutedStrong,fontSize:12},empty:{paddingVertical:34},emptyTitle:{color:C.white,fontFamily:F.black,fontSize:18},emptyBody:{color:C.mutedStrong,fontSize:11,lineHeight:17,marginTop:7},action:{height:44,backgroundColor:C.lime,alignItems:'center',justifyContent:'center',marginTop:18},actionText:{color:C.black,fontFamily:F.extraBold,fontSize:8,letterSpacing:1},card:{paddingVertical:18,borderBottomWidth:1,borderBottomColor:C.borderStrong},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},status:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:.7},title:{color:C.white,fontFamily:F.extraBold,fontSize:17,marginTop:10},price:{color:C.mutedStrong,fontSize:11,marginTop:7},location:{color:C.muted,fontSize:10,marginTop:4},updated:{color:C.muted,fontFamily:F.extraBold,fontSize:7,letterSpacing:.7,marginTop:12}});