import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame, PageHeader, InlineBadge } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { MarketplaceClaim, MarketplaceQuota, loadMarketplaceQuota, loadMyMarketplaceClaims } from '@/core/marketplace/marketplace-service';

const LABEL:Record<string,string>={requested:'REQUESTED',approved:'APPROVED',ready:'READY FOR PICKUP',picked_up:'PICKED UP',cancelled:'CANCELLED',expired:'EXPIRED',declined:'NOT SELECTED',no_show:'NO-SHOW'};
export default function MarketplaceClaims(){
 const [rows,setRows]=useState<MarketplaceClaim[]>([]);const [quota,setQuota]=useState<MarketplaceQuota|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(()=>{setLoading(true);setError('');Promise.all([loadMyMarketplaceClaims(),loadMarketplaceQuota()]).then(([a,b])=>{setRows(a);setQuota(b)}).catch(e=>setError(e?.message==='SIGNED_OUT'?'Sign in to see your Marketplace claims.':'Claims could not be loaded.')).finally(()=>setLoading(false))},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 return <ScreenFrame><PageHeader eyebrow="FAIRPATH MARKETPLACE" title="My claims" backTo="/marketplace"/><ScrollView contentContainerStyle={s.content}>
  {quota?<View style={s.quota}><Text style={s.quotaLabel}>{quota.plan==='fairpath_plus'?'FAIRPATH+':'FREE PLAN'}</Text><Text style={s.quotaTitle}>{quota.remaining} claim{quota.remaining===1?'':'s'} remaining</Text><Text style={s.quotaBody}>{quota.used} of {quota.monthly_limit} used this month</Text></View>:null}
  {loading?<Text style={s.state}>Loading claims…</Text>:error?<Text style={s.error}>{error}</Text>:rows.length===0?<View style={s.empty}><Lucide name="gift" color={C.mutedStrong} size={26}/><Text style={s.emptyTitle}>No claims yet.</Text><Text style={s.emptyBody}>When you request a free item, its status and pickup window will live here.</Text><Pressable style={s.primary} onPress={()=>router.replace('/marketplace' as never)}><Text style={s.primaryText}>FIND FREE ITEMS</Text></Pressable></View>:rows.map(c=>{const photo=c.item?.marketplace_media?.slice().sort((a,b)=>a.sort_order-b.sort_order)[0]?.url??'';return <Pressable key={c.id} style={s.row} onPress={()=>router.push(('/marketplace-claim/'+c.id) as never)}>
   <View style={s.media}>{photo?<Image source={{uri:photo}} style={s.photo}/>:<View style={s.noPhoto}><Lucide name="image-off" color={C.mutedStrong} size={18}/></View>}</View>
   <View style={s.copy}><InlineBadge tone={['approved','ready'].includes(c.status)?'lime':undefined}>{LABEL[c.status]??c.status.toUpperCase()}</InlineBadge><Text style={s.title}>{c.item?.title??'Marketplace item'}</Text><Text style={s.meta}>{c.item?[c.item.pickup_area||c.item.city,c.item.state].filter(Boolean).join(', '):''}</Text>{c.pickup_deadline&&['approved','ready'].includes(c.status)?<Text style={s.deadline}>PICK UP BY {new Date(c.pickup_deadline).toLocaleString()}</Text>:null}</View><Lucide name="arrow-right" color={C.lime} size={15}/>
  </Pressable>})}
 </ScrollView></ScreenFrame>
}
const s=StyleSheet.create({content:{paddingHorizontal:L.mobileGutter,paddingBottom:40},quota:{borderBottomWidth:1,borderBottomColor:C.borderStrong,paddingVertical:15},quotaLabel:{color:C.lime,fontFamily:F.extraBold,fontSize:7,letterSpacing:1},quotaTitle:{color:C.white,fontFamily:F.black,fontSize:20,marginTop:4},quotaBody:{color:C.muted,fontSize:9,marginTop:4},state:{color:C.mutedStrong,paddingVertical:24},error:{color:C.danger,paddingVertical:24},row:{minHeight:118,borderBottomWidth:1,borderBottomColor:C.borderStrong,flexDirection:'row',gap:10,alignItems:'center',paddingVertical:11},media:{width:86,height:86,borderWidth:1,borderColor:C.borderStrong,backgroundColor:'#0A0C0A'},photo:{width:'100%',height:'100%'},noPhoto:{flex:1,alignItems:'center',justifyContent:'center'},copy:{flex:1,minWidth:0},title:{color:C.white,fontFamily:F.extraBold,fontSize:13,marginTop:7},meta:{color:C.muted,fontSize:8.5,marginTop:4},deadline:{color:C.lime,fontFamily:F.extraBold,fontSize:7,marginTop:6},empty:{paddingVertical:36},emptyTitle:{color:C.white,fontFamily:F.black,fontSize:21,marginTop:12},emptyBody:{color:C.muted,fontSize:10,lineHeight:16,marginTop:5,maxWidth:310},primary:{height:46,backgroundColor:C.lime,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8}});