import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { notify } from '@/core/ui/notify';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame, PageHeader, InlineBadge } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { MarketplaceItem, loadMyMarketplaceListings, removeMarketplaceItem } from '@/core/marketplace/marketplace-service';

export default function MarketplaceMyListings(){
 const [rows,setRows]=useState<MarketplaceItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(()=>{setLoading(true);setError('');loadMyMarketplaceListings().then(setRows).catch(e=>setError(e?.message==='SIGNED_OUT'?'Sign in to manage Marketplace listings.':'Listings could not be loaded.')).finally(()=>setLoading(false))},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 function remove(item:MarketplaceItem){notify('Remove listing?','Active claims will be cancelled and released from quota where appropriate.',[{text:'Keep',style:'cancel'},{text:'Remove',style:'destructive',onPress:async()=>{try{await removeMarketplaceItem(item.id);await load()}catch{notify('Could not remove listing','Please try again.')}}}])}
 return <ScreenFrame><PageHeader eyebrow="FAIRPATH MARKETPLACE" title="My listings" backTo="/marketplace" trailing={<Pressable style={s.add} onPress={()=>router.push('/marketplace-list-item' as never)}><Lucide name="plus" color={C.black} size={15}/></Pressable>}/><ScrollView contentContainerStyle={s.content}>
  {loading?<Text style={s.state}>Loading listings…</Text>:error?<Text style={s.error}>{error}</Text>:rows.length===0?<View style={s.empty}><Lucide name="package-plus" color={C.mutedStrong} size={28}/><Text style={s.emptyTitle}>Nothing listed yet.</Text><Text style={s.emptyBody}>Give useful items forward through FairPath Marketplace.</Text><Pressable style={s.primary} onPress={()=>router.push('/marketplace-list-item' as never)}><Text style={s.primaryText}>LIST A FREE ITEM</Text></Pressable></View>:rows.map(item=>{const photo=item.marketplace_media?.slice().sort((a,b)=>a.sort_order-b.sort_order)[0]?.url??'';return <View key={item.id} style={s.card}>
   <Pressable style={s.cardMain} onPress={()=>router.push(('/marketplace-manage/'+item.id) as never)}><View style={s.media}>{photo?<Image source={{uri:photo}} style={s.photo}/>:<View style={s.noPhoto}><Lucide name="image-off" color={C.mutedStrong} size={18}/></View>}</View><View style={s.copy}><View style={s.badges}><InlineBadge tone={item.status==='available'?'lime':undefined}>{item.status.replaceAll('_',' ').toUpperCase()}</InlineBadge></View><Text style={s.title}>{item.title}</Text><Text style={s.meta}>{item.pickup_area||item.city+', '+item.state}</Text><Text style={s.meta}>{item.marketplace_media?.length??0} photo{(item.marketplace_media?.length??0)===1?'':'s'}</Text></View><Lucide name="arrow-right" color={C.lime} size={15}/></Pressable>
   {item.status!=='removed'&&item.status!=='claimed'?<Pressable style={s.remove} onPress={()=>remove(item)}><Text style={s.removeText}>REMOVE LISTING</Text></Pressable>:null}
  </View>})}
 </ScrollView></ScreenFrame>
}
const s=StyleSheet.create({content:{paddingHorizontal:L.mobileGutter,paddingBottom:40},add:{width:34,height:34,backgroundColor:C.lime,alignItems:'center',justifyContent:'center'},state:{color:C.mutedStrong,paddingVertical:24},error:{color:C.danger,paddingVertical:24},card:{borderBottomWidth:1,borderBottomColor:C.borderStrong,paddingVertical:11},cardMain:{minHeight:104,flexDirection:'row',gap:10,alignItems:'center'},media:{width:88,height:88,borderWidth:1,borderColor:C.borderStrong,backgroundColor:'#0A0C0A'},photo:{width:'100%',height:'100%'},noPhoto:{flex:1,alignItems:'center',justifyContent:'center'},copy:{flex:1,minWidth:0},badges:{flexDirection:'row'},title:{color:C.white,fontFamily:F.extraBold,fontSize:14,marginTop:7},meta:{color:C.muted,fontSize:8.5,marginTop:4},remove:{height:34,borderTopWidth:1,borderTopColor:C.border,alignItems:'center',justifyContent:'center'},removeText:{color:C.danger,fontFamily:F.extraBold,fontSize:7,letterSpacing:.8},empty:{paddingVertical:36},emptyTitle:{color:C.white,fontFamily:F.black,fontSize:21,marginTop:12},emptyBody:{color:C.muted,fontSize:10,lineHeight:16,marginTop:5},primary:{height:46,backgroundColor:C.lime,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8}});