import { useMemo, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Lucide } from '@react-native-vector-icons/lucide';
import { FairPathColors as C, FairPathFonts as F } from '@/constants/fairpath';

const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
function parse(text:string){const m=text.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)return null;const d=new Date(Number(m[3]),Number(m[1])-1,Number(m[2]));return Number.isNaN(d.getTime())?null:d}
function fmt(d:Date){return String(d.getMonth()+1).padStart(2,'0')+'/'+String(d.getDate()).padStart(2,'0')+'/'+d.getFullYear()}
export function SimpleDatePicker({label,value,onChange,minDate,maxDate,error}:{label:string;value:string;onChange:(value:string)=>void;minDate?:Date;maxDate?:Date;error?:string}){
 const initial=parse(value)??minDate??maxDate??new Date();
 const [open,setOpen]=useState(false);const [cursor,setCursor]=useState(new Date(initial.getFullYear(),initial.getMonth(),1));
 const days=useMemo(()=>{const first=cursor.getDay(),count=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:count},(_,i)=>i+1)]},[cursor]);
 function choose(day:number){const d=new Date(cursor.getFullYear(),cursor.getMonth(),day);if(minDate&&d<new Date(minDate.getFullYear(),minDate.getMonth(),minDate.getDate()))return;if(maxDate&&d>new Date(maxDate.getFullYear(),maxDate.getMonth(),maxDate.getDate()))return;onChange(fmt(d));setOpen(false)}
 return <View style={s.wrap}><Text style={s.label}>{label}</Text><Pressable style={[s.field,error&&s.fieldError]} onPress={()=>setOpen(true)}><Text style={[s.value,!value&&s.placeholder]}>{value||'Select a date'}</Text><Lucide name="calendar-days" color={C.lime} size={16}/></Pressable>{error?<Text style={s.error}>{error}</Text>:null}
 <Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><View style={s.card}><View style={s.head}><Pressable style={s.arrow} onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><Lucide name="chevron-left" color={C.white} size={18}/></Pressable><Text style={s.month}>{MONTHS[cursor.getMonth()]} {cursor.getFullYear()}</Text><Pressable style={s.arrow} onPress={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><Lucide name="chevron-right" color={C.white} size={18}/></Pressable></View><View style={s.week}>{['S','M','T','W','T','F','S'].map((x,i)=><Text key={x+i} style={s.weekText}>{x}</Text>)}</View><View style={s.grid}>{days.map((day,i)=>{if(!day)return <View key={'e'+i} style={s.day}/>;const d=new Date(cursor.getFullYear(),cursor.getMonth(),day);const disabled=Boolean((minDate&&d<new Date(minDate.getFullYear(),minDate.getMonth(),minDate.getDate()))||(maxDate&&d>new Date(maxDate.getFullYear(),maxDate.getMonth(),maxDate.getDate())));const selected=value===fmt(d);return <Pressable key={day} disabled={disabled} onPress={()=>choose(day)} style={[s.day,selected&&s.selected]}><Text style={[s.dayText,disabled&&s.disabled,selected&&s.selectedText]}>{day}</Text></Pressable>})}</View><Pressable style={s.close} onPress={()=>setOpen(false)}><Text style={s.closeText}>CANCEL</Text></Pressable></View></View></Modal></View>
}
const s=StyleSheet.create({wrap:{marginTop:14},label:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1,marginBottom:7},field:{minHeight:48,borderWidth:1,borderColor:C.borderStrong,paddingHorizontal:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},fieldError:{borderColor:C.danger},value:{color:C.white,fontSize:13},placeholder:{color:C.muted},error:{color:C.danger,fontSize:9,marginTop:5},overlay:{flex:1,backgroundColor:'#000000CC',alignItems:'center',justifyContent:'center',padding:20},card:{width:'100%',maxWidth:390,backgroundColor:'#0B0D0B',borderWidth:1,borderColor:C.borderStrong,padding:14},head:{height:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},arrow:{width:38,height:38,alignItems:'center',justifyContent:'center'},month:{color:C.white,fontFamily:F.extraBold,fontSize:14},week:{flexDirection:'row',marginTop:8},weekText:{width:'14.285%',textAlign:'center',color:C.muted,fontFamily:F.extraBold,fontSize:8},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:6},day:{width:'14.285%',height:42,alignItems:'center',justifyContent:'center'},dayText:{color:C.white,fontSize:11},disabled:{color:'#444'},selected:{backgroundColor:C.lime},selectedText:{color:C.black,fontFamily:F.extraBold},close:{height:42,borderWidth:1,borderColor:C.borderStrong,alignItems:'center',justifyContent:'center',marginTop:10},closeText:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8}});
