import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ScreenFrame, PageHeader } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { reportMarketplaceItem } from '@/core/marketplace/marketplace-service';

const REASONS=['Unsafe item','Prohibited item','Misleading listing','Scam / fraud concern','Discriminatory behavior','Pickup safety concern','Other'];
export default function MarketplaceReport(){
 const {id}=useLocalSearchParams<{id:string}>();const [reason,setReason]=useState('');const [details,setDetails]=useState('');const [sending,setSending]=useState(false);
 async function submit(){if(!id||sending)return;if(!reason){Alert.alert('Choose a reason','Tell FairPath what should be reviewed.');return}setSending(true);try{await reportMarketplaceItem(id,reason,details);Alert.alert('Report received','FairPath saved this report for Admin review. The listing is not automatically removed unless a safety rule requires it.',[{text:'Done',onPress:()=>router.replace(('/market-item/'+id) as never)}])}catch(e){if(e instanceof Error&&e.message==='SIGNED_OUT'){router.replace(('/sign-up?returnTo='+encodeURIComponent('/marketplace-report/'+id)) as never);return}Alert.alert('Could not submit report','Please try again.')}finally{setSending(false)}}
 return <ScreenFrame><PageHeader eyebrow="FAIRPATH MARKETPLACE" title="Report item" backTo={id?'/market-item/'+id:'/marketplace'}/><ScrollView contentContainerStyle={s.content}><Text style={s.intro}>Use reports for prohibited items, misleading listings, discriminatory behavior, fraud, or pickup safety concerns.</Text><Text style={s.label}>REASON</Text><View style={s.options}>{REASONS.map(x=><Pressable key={x} style={[s.option,reason===x&&s.optionOn]} onPress={()=>setReason(x)}><Text style={[s.optionText,reason===x&&s.optionTextOn]}>{x.toUpperCase()}</Text></Pressable>)}</View><Text style={s.label}>DETAILS · OPTIONAL</Text><TextInput value={details} onChangeText={setDetails} style={s.area} multiline maxLength={1500} textAlignVertical="top" placeholder="Add details that can help FairPath review this safely." placeholderTextColor={C.muted}/><Pressable style={[s.primary,sending&&s.disabled]} disabled={sending} onPress={()=>void submit()}><Text style={s.primaryText}>{sending?'SENDING…':'SUBMIT REPORT'}</Text></Pressable></ScrollView></ScreenFrame>
}
const s=StyleSheet.create({content:{padding:L.mobileGutter,paddingBottom:40},intro:{color:C.mutedStrong,fontSize:10,lineHeight:16},label:{color:C.lime,fontFamily:F.extraBold,fontSize:7,letterSpacing:1,marginTop:18,marginBottom:7},options:{gap:6},option:{minHeight:42,borderWidth:1,borderColor:C.borderStrong,paddingHorizontal:11,justifyContent:'center'},optionOn:{borderColor:C.lime,backgroundColor:'#0F150B'},optionText:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:7},optionTextOn:{color:C.lime},area:{minHeight:130,borderWidth:1,borderColor:C.borderStrong,color:C.white,padding:10,fontSize:10},primary:{height:48,backgroundColor:C.lime,alignItems:'center',justifyContent:'center',marginTop:15},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:8,letterSpacing:.8},disabled:{opacity:.55}});