import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { notify } from '@/core/ui/notify';
import * as DocumentPicker from 'expo-document-picker';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame, PageHeader } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import {
 MARKETPLACE_CATEGORIES, MARKETPLACE_CONDITIONS, MarketplaceItem, MarketplaceMedia, MarketplacePickupDetails,
 loadMarketplaceItem, loadMarketplacePickupDetailsForSeller, removeMarketplacePhoto, reorderMarketplacePhotos,
 setMarketplaceItemAvailability, updateMarketplaceItem, uploadMarketplacePhoto
} from '@/core/marketplace/marketplace-service';
import { formatUsPhone } from '@/core/forms/formatters';

export default function MarketplaceEdit(){
 const {id}=useLocalSearchParams<{id:string}>();
 const [item,setItem]=useState<MarketplaceItem|null>(null);const [pickup,setPickup]=useState<MarketplacePickupDetails|null>(null);
 const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [category,setCategory]=useState('');const [condition,setCondition]=useState('');const [quantity,setQuantity]=useState('1');const [city,setCity]=useState('');const [state,setState]=useState('');const [postal,setPostal]=useState('');const [pickupArea,setPickupArea]=useState('');const [safePickup,setSafePickup]=useState(true);const [sellerType,setSellerType]=useState<'individual'|'organization'>('individual');
 const [locationName,setLocationName]=useState('');const [address1,setAddress1]=useState('');const [address2,setAddress2]=useState('');const [pickupCity,setPickupCity]=useState('');const [pickupState,setPickupState]=useState('');const [pickupPostal,setPickupPostal]=useState('');const [instructions,setInstructions]=useState('');const [contactPhone,setContactPhone]=useState('');
 const [media,setMedia]=useState<MarketplaceMedia[]>([]);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');

 const load=useCallback(()=>{if(!id)return;setLoading(true);setError('');Promise.all([loadMarketplaceItem(id),loadMarketplacePickupDetailsForSeller(id)]).then(([a,b])=>{setItem(a);setPickup(b);setTitle(a.title);setDescription(a.description);setCategory(a.category);setCondition(a.condition??'');setQuantity(String(a.quantity));setCity(a.city);setState(a.state);setPostal(a.postal_code??'');setPickupArea(a.pickup_area??'');setSafePickup(a.safe_pickup);setSellerType(a.seller_type);setMedia(a.marketplace_media?.slice().sort((x,y)=>x.sort_order-y.sort_order)??[]);setLocationName(b?.location_name??'');setAddress1(b?.address_line1??'');setAddress2(b?.address_line2??'');setPickupCity(b?.city??a.city);setPickupState(b?.state??a.state);setPickupPostal(b?.postal_code??'');setInstructions(b?.instructions??'');setContactPhone(b?.contact_phone??'')}).catch(()=>setError('This listing could not be loaded for editing.')).finally(()=>setLoading(false))},[id]);
 useFocusEffect(useCallback(()=>{load()},[load]));

 async function save(){
  if(!id||saving)return;if(title.trim().length<3||description.trim().length<10||!category||!condition||!city.trim()||state.length<2||!pickupCity.trim()||pickupState.length<2){notify('Finish the listing','Complete the required title, description, category, condition and pickup location fields.');return}
  setSaving(true);try{await updateMarketplaceItem(id,{title,description,category,condition,quantity:Number(quantity)||1,city,state,postal_code:postal,pickup_area:pickupArea,safe_pickup:safePickup,seller_type:sellerType,location_name:locationName,address_line1:address1,address_line2:address2,pickup_city:pickupCity,pickup_state:pickupState,pickup_postal_code:pickupPostal,instructions,contact_phone:contactPhone});notify('Listing updated','Changes are live.',[{text:'Done',onPress:()=>router.replace(('/marketplace-manage/'+id) as never)}])}catch{notify('Could not update','Please try again.')}finally{setSaving(false)}
 }
 async function addPhotos(){if(!id||media.length>=20)return;const r=await DocumentPicker.getDocumentAsync({multiple:true,copyToCacheDirectory:true,type:['image/jpeg','image/png','image/heic','image/heif','image/webp']});if(r.canceled)return;let next=[...media];for(const asset of r.assets.slice(0,20-media.length)){if((asset.size??0)>12*1024*1024)continue;try{const resp=await fetch(asset.uri);const bytes=await resp.arrayBuffer();await uploadMarketplacePhoto(id,{name:asset.name,mimeType:asset.mimeType,bytes},next.length);const refreshed=await loadMarketplaceItem(id);next=refreshed.marketplace_media?.slice().sort((a,b)=>a.sort_order-b.sort_order)??next}catch{}}setMedia(next)}
 async function removePhoto(photo:MarketplaceMedia){try{await removeMarketplacePhoto(photo);const next=media.filter(x=>x.id!==photo.id);await reorderMarketplacePhotos(id!,next);setMedia(next.map((x,i)=>({...x,sort_order:i})))}catch{notify('Could not remove photo','Please try again.')}}
 async function move(index:number,dir:-1|1){const target=index+dir;if(target<0||target>=media.length||!id)return;const next=[...media];[next[index],next[target]]=[next[target],next[index]];setMedia(next);try{await reorderMarketplacePhotos(id,next)}catch{await load()}}
 async function toggleAvailability(){if(!item||!id)return;try{await setMarketplaceItemAvailability(id,item.status!=='available');await load()}catch(e){notify(e instanceof Error&&e.message==='STATUS_LOCKED'?'Listing status locked':'Could not update status',e instanceof Error&&e.message==='STATUS_LOCKED'?'A reserved, claimed, or removed item cannot be paused or relisted.':'Please try again.')}}
 if(loading)return <ScreenFrame><PageHeader eyebrow="FAIRPATH MARKETPLACE" title="Edit listing"/><Text style={s.state}>Loading listing…</Text></ScreenFrame>;
 if(error||!item)return <ScreenFrame><PageHeader eyebrow="FAIRPATH MARKETPLACE" title="Edit listing"/><Text style={s.error}>{error||'Listing not found.'}</Text></ScreenFrame>;
 return <ScreenFrame><PageHeader eyebrow="FAIRPATH MARKETPLACE" title="Edit listing" backTo={'/marketplace-manage/'+item.id}/><ScrollView contentContainerStyle={s.content}>
  <View style={s.status}><View><Text style={s.labelTop}>LISTING STATUS</Text><Text style={s.statusTitle}>{item.status.replaceAll('_',' ').toUpperCase()}</Text></View>{['available','paused'].includes(item.status)?<Pressable style={s.statusBtn} onPress={()=>void toggleAvailability()}><Text style={s.statusBtnText}>{item.status==='available'?'PAUSE':'RELIST'}</Text></Pressable>:null}</View>
  <Label text="TITLE"/><TextInput value={title} onChangeText={setTitle} style={s.field}/>
  <Label text="DESCRIPTION"/><TextInput value={description} onChangeText={setDescription} style={s.area} multiline textAlignVertical="top"/>
  <Label text="CATEGORY"/><View style={s.chips}>{MARKETPLACE_CATEGORIES.map(x=><Chip key={x} label={x} active={category===x} onPress={()=>setCategory(x)}/>)}</View>
  <Label text="CONDITION"/><View style={s.chips}>{MARKETPLACE_CONDITIONS.map(x=><Chip key={x} label={x} active={condition===x} onPress={()=>setCondition(x)}/>)}</View>
  <View style={s.two}><View style={{flex:1}}><Label text="QUANTITY"/><TextInput value={quantity} onChangeText={v=>setQuantity(v.replace(/D/g,'').slice(0,2))} keyboardType="number-pad" style={s.field}/></View><View style={{flex:1}}><Label text="DONOR TYPE"/><View style={s.chips}><Chip label="Individual" active={sellerType==='individual'} onPress={()=>setSellerType('individual')}/><Chip label="Organization" active={sellerType==='organization'} onPress={()=>setSellerType('organization')}/></View></View></View>
  <Text style={s.sectionTitle}>PUBLIC LOCATION</Text><View style={s.two}><TextInput value={city} onChangeText={setCity} style={[s.field,{flex:1}]} placeholder="City" placeholderTextColor={C.muted}/><TextInput value={state} onChangeText={v=>setState(v.toUpperCase().slice(0,2))} style={[s.field,{width:78}]} placeholder="OH" placeholderTextColor={C.muted}/></View><TextInput value={postal} onChangeText={setPostal} style={s.field} placeholder="ZIP" placeholderTextColor={C.muted}/><TextInput value={pickupArea} onChangeText={setPickupArea} style={s.field} placeholder="Pickup area label" placeholderTextColor={C.muted}/>
  <Text style={s.sectionTitle}>PRIVATE PICKUP</Text><TextInput value={locationName} onChangeText={setLocationName} style={s.field} placeholder="Location name" placeholderTextColor={C.muted}/><TextInput value={address1} onChangeText={setAddress1} style={s.field} placeholder="Street address" placeholderTextColor={C.muted}/><TextInput value={address2} onChangeText={setAddress2} style={s.field} placeholder="Unit / suite" placeholderTextColor={C.muted}/><View style={s.two}><TextInput value={pickupCity} onChangeText={setPickupCity} style={[s.field,{flex:1}]} placeholder="City" placeholderTextColor={C.muted}/><TextInput value={pickupState} onChangeText={v=>setPickupState(v.toUpperCase().slice(0,2))} style={[s.field,{width:78}]} placeholder="OH" placeholderTextColor={C.muted}/></View><TextInput value={pickupPostal} onChangeText={setPickupPostal} style={s.field} placeholder="ZIP" placeholderTextColor={C.muted}/><TextInput value={instructions} onChangeText={setInstructions} style={s.areaSmall} multiline textAlignVertical="top" placeholder="Pickup instructions" placeholderTextColor={C.muted}/><TextInput value={formatUsPhone(contactPhone)} onChangeText={v=>setContactPhone(formatUsPhone(v))} style={s.field} keyboardType="phone-pad" placeholder="Contact phone" placeholderTextColor={C.muted}/>
  <Pressable style={[s.safe,safePickup&&s.safeOn]} onPress={()=>setSafePickup(v=>!v)}><View style={[s.box,safePickup&&s.boxOn]}>{safePickup?<Lucide name="check" color={C.black} size={12}/>:null}</View><Text style={s.safeText}>SAFE PICKUP</Text></Pressable>
  <Text style={s.sectionTitle}>PHOTOS</Text><Text style={s.help}>First photo is the cover. Reorder with arrows. Maximum 20.</Text><Pressable style={s.addPhotos} onPress={()=>void addPhotos()}><Lucide name="image-plus" color={C.lime} size={15}/><Text style={s.addText}>ADD PHOTOS</Text><Text style={s.count}>{media.length}/20</Text></Pressable>
  <View>{media.map((m,i)=><View key={m.id} style={s.photoRow}><Image source={{uri:m.url}} style={s.thumb}/><View style={s.photoCopy}><Text style={s.photoLabel}>{i===0?'COVER PHOTO':'PHOTO '+(i+1)}</Text><Text style={s.photoMeta}>{m.mime_type??'image'}</Text></View><Pressable style={s.iconBtn} onPress={()=>void move(i,-1)}><Lucide name="arrow-up" color={C.mutedStrong} size={14}/></Pressable><Pressable style={s.iconBtn} onPress={()=>void move(i,1)}><Lucide name="arrow-down" color={C.mutedStrong} size={14}/></Pressable><Pressable style={s.iconBtn} onPress={()=>void removePhoto(m)}><Lucide name="trash-2" color={C.danger} size={14}/></Pressable></View>)}</View>
  <Pressable style={[s.saveBtn,saving&&s.disabled]} disabled={saving} onPress={()=>void save()}><Text style={s.saveText}>{saving?'SAVING…':'SAVE CHANGES'}</Text><Lucide name="arrow-right" color={C.black} size={15}/></Pressable>
 </ScrollView></ScreenFrame>
}
function Label({text}:{text:string}){return <Text style={s.label}>{text}</Text>}function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable style={[s.chip,active&&s.chipOn]} onPress={onPress}><Text style={[s.chipText,active&&s.chipTextOn]}>{label.toUpperCase()}</Text></Pressable>}
const s=StyleSheet.create({content:{padding:L.mobileGutter,paddingBottom:42},state:{color:C.mutedStrong,padding:L.mobileGutter},error:{color:C.danger,padding:L.mobileGutter},status:{minHeight:66,borderBottomWidth:1,borderBottomColor:C.borderStrong,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},labelTop:{color:C.lime,fontFamily:F.extraBold,fontSize:7,letterSpacing:1},statusTitle:{color:C.white,fontFamily:F.black,fontSize:17,marginTop:4},statusBtn:{height:34,borderWidth:1,borderColor:C.borderStrong,paddingHorizontal:11,justifyContent:'center'},statusBtnText:{color:C.white,fontFamily:F.extraBold,fontSize:7,letterSpacing:.8},label:{color:C.lime,fontFamily:F.extraBold,fontSize:7,letterSpacing:1,marginTop:15,marginBottom:6},field:{minHeight:45,borderWidth:1,borderColor:C.borderStrong,color:C.white,paddingHorizontal:10,fontSize:10,marginBottom:7},area:{minHeight:120,borderWidth:1,borderColor:C.borderStrong,color:C.white,padding:10,fontSize:10},areaSmall:{minHeight:86,borderWidth:1,borderColor:C.borderStrong,color:C.white,padding:10,fontSize:10,marginBottom:7},chips:{flexDirection:'row',flexWrap:'wrap',gap:5},chip:{minHeight:34,borderWidth:1,borderColor:C.borderStrong,paddingHorizontal:8,alignItems:'center',justifyContent:'center'},chipOn:{backgroundColor:C.lime,borderColor:C.lime},chipText:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:6.3},chipTextOn:{color:C.black},two:{flexDirection:'row',gap:8},sectionTitle:{color:C.white,fontFamily:F.black,fontSize:17,marginTop:22,marginBottom:9},safe:{height:44,borderWidth:1,borderColor:C.borderStrong,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:10},safeOn:{borderColor:'#526F2B',backgroundColor:'#0F150B'},box:{width:19,height:19,borderWidth:1,borderColor:C.borderStrong,alignItems:'center',justifyContent:'center'},boxOn:{backgroundColor:C.lime,borderColor:C.lime},safeText:{color:C.white,fontFamily:F.extraBold,fontSize:7.5,letterSpacing:.7},help:{color:C.muted,fontSize:8.5,lineHeight:13,marginBottom:8},addPhotos:{height:44,borderWidth:1,borderColor:C.borderStrong,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:10},addText:{flex:1,color:C.white,fontFamily:F.extraBold,fontSize:7.5,letterSpacing:.7},count:{color:C.lime,fontFamily:F.extraBold,fontSize:8},photoRow:{minHeight:68,borderBottomWidth:1,borderBottomColor:C.border,flexDirection:'row',alignItems:'center',gap:7},thumb:{width:62,height:54},photoCopy:{flex:1,minWidth:0},photoLabel:{color:C.white,fontFamily:F.extraBold,fontSize:8},photoMeta:{color:C.muted,fontSize:7,marginTop:3},iconBtn:{width:32,height:32,alignItems:'center',justifyContent:'center'},saveBtn:{height:50,backgroundColor:C.lime,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:13,marginTop:18},saveText:{color:C.black,fontFamily:F.extraBold,fontSize:8.5,letterSpacing:.8},disabled:{opacity:.55}});