-- Harden Record Relief AI uploads and packet ownership before deployment.
alter table public.record_relief_uploads add column if not exists expires_at timestamptz not null default (now()+interval '30 days');
alter table public.record_relief_uploads add column if not exists consented_at timestamptz;
alter table public.record_relief_uploads add column if not exists consent_version text;
create index if not exists record_relief_uploads_expiry_idx on public.record_relief_uploads(expires_at) where status<>'deleted';
drop policy if exists "members update own relief uploads" on public.record_relief_uploads;
revoke update on table public.record_relief_uploads from authenticated;
create or replace function public.create_record_relief_packet() returns uuid language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid(); pid uuid;begin if uid is null then raise exception 'SIGNED_OUT';end if;insert into public.record_relief_case_packets(user_id) values(uid) returning id into pid;return pid;end$$;
create or replace function public.attach_record_relief_upload(p_upload uuid,p_packet uuid) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();begin if uid is null then raise exception 'SIGNED_OUT';end if;if not exists(select 1 from public.record_relief_uploads where id=p_upload and user_id=uid) or not exists(select 1 from public.record_relief_case_packets where id=p_packet and user_id=uid) then raise exception 'PACKET_UNAVAILABLE';end if;update public.record_relief_uploads set packet_id=p_packet where id=p_upload and user_id=uid;end$$;
create or replace function public.confirm_record_relief_packet(p_packet uuid,p_case uuid,p_merged jsonb,p_conflicts jsonb default '[]'::jsonb) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();begin if uid is null then raise exception 'SIGNED_OUT';end if;if not exists(select 1 from public.record_relief_cases where id=p_case and user_id=uid) then raise exception 'CASE_UNAVAILABLE';end if;update public.record_relief_case_packets set case_id=p_case,status='confirmed',merged_extraction=p_merged,conflicts=coalesce(p_conflicts,'[]'::jsonb),confirmed_at=now(),updated_at=now() where id=p_packet and user_id=uid;if not found then raise exception 'PACKET_UNAVAILABLE';end if;end$$;
revoke all on function public.create_record_relief_packet() from public,anon;revoke all on function public.attach_record_relief_upload(uuid,uuid) from public,anon;revoke all on function public.confirm_record_relief_packet(uuid,uuid,jsonb,jsonb) from public,anon;grant execute on function public.create_record_relief_packet() to authenticated;grant execute on function public.attach_record_relief_upload(uuid,uuid) to authenticated;grant execute on function public.confirm_record_relief_packet(uuid,uuid,jsonb,jsonb) to authenticated;