import {router,useLocalSearchParams} from 'expo-router';import {useEffect,useState} from 'react';import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';import {ScreenFrame,PageHeader,InlineBadge} from '@/components/ProductChrome';import {FairPathColors as C,FairPathFonts as F,FairPathLayout as L} from '@/constants/fairpath';import {HousingApplicationForm,loadHousingApplicationForm,loadMyHousingApplicationDetail,saveHousingApplicationDraft,submitHousingApplication} from '@/core/opportunities/opportunity-service';
const EMPTY:HousingApplicationForm={first_name:'',last_name:'',email:'',phone:'',date_of_birth:'',current_address:'',monthly_income:'',employer:'',employment_status:'',move_in_date:'',occupants:'',pets:'',housing_history:'',references:'',additional_notes:''};
const STEPS=['APPLICANT','INCOME','HOUSEHOLD','HISTORY','REVIEW'];
export default function Apply(){const {id}=useLocalSearchParams<{id:string}>();const [form,setForm]=useState(EMPTY),[step,setStep]=useState(1),[fast,setFast]=useState(false),[title,setTitle]=useState('Housing application'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
useEffect(()=>{if(!id)return;Promise.all([loadHousingApplicationForm(id),loadMyHousingApplicationDetail(id)]).then(([x,a])=>{setForm(x.form);setStep(Math.min(x.current_step,5));setFast(a.application_type==='fasttrack');setTitle(a.listing?.title??'Housing application')}).catch(()=>Alert.alert('Could not load application','Please try again.')).finally(()=>setLoading(false))},[id]);
const set=(k:keyof HousingApplicationForm,v:string)=>setForm(x=>({...x,[k]:v}));const next=async()=>{if(!id)return;setSaving(true);try{const n=Math.min(step+1,5);await saveHousingApplicationDraft(id,form,n);setStep(n)}finally{setSaving(false)}};const back=()=>step>1?setStep(step-1):router.back();const submit=()=>Alert.alert('Submit application?','Review your answers first. Submitting sends this application into the FairPath application workflow. This does not guarantee approval.',[{text:'Cancel',style:'cancel'},{text:'Submit',onPress:async()=>{if(!id)return;setSaving(true);try{await submitHousingApplication(id,form);router.replace(('/housing-application/'+id) as never)}catch{Alert.alert('Could not submit','Please try again.')}finally{setSaving(false)}}}]);
if(loading)return <ScreenFrame><PageHeader eyebrow="FAIRPATH HOUSING" title="Application" backTo="/housing-applications"/><Text style={s.loading}>Loading application…</Text></ScreenFrame>;
return <ScreenFrame><PageHeader eyebrow={fast?'FASTTRACK APPLICATION':'STANDARD APPLICATION'} title={title} onBack={back}/><View style={s.progress}>{STEPS.map((x,i)=><View key={x} style={s.piece}><View style={[s.bar,i<step&&s.barOn]}/><Text style={[s.step,i===step-1&&s.stepOn]}>{x}</Text></View>)}</View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
{fast?<View style={s.fast}><InlineBadge tone="lime">FASTTRACK</InlineBadge><Text style={s.fastText}>We prefill confirmed FairPath information where available. You still review every answer before submission.</Text></View>:null}
{step===1?<><H title="Applicant information"/><Field label="FIRST NAME" value={form.first_name} set={v=>set('first_name',v)}/><Field label="LAST NAME" value={form.last_name} set={v=>set('last_name',v)}/><Field label="EMAIL" value={form.email} set={v=>set('email',v)}/><Field label="PHONE" value={form.phone} set={v=>set('phone',v)}/><Field label="DATE OF BIRTH" value={form.date_of_birth} set={v=>set('date_of_birth',v)}/><Field label="CURRENT ADDRESS" value={form.current_address} set={v=>set('current_address',v)}/></>:null}
{step===2?<><H title="Income & employment"/><Field label="EMPLOYMENT STATUS" value={form.employment_status} set={v=>set('employment_status',v)}/><Field label="EMPLOYER / INCOME SOURCE" value={form.employer} set={v=>set('employer',v)}/><Field label="GROSS MONTHLY INCOME" value={form.monthly_income} set={v=>set('monthly_income',v)} keyboard="numeric"/></>:null}
{step===3?<><H title="Move-in & household"/><Field label="DESIRED MOVE-IN DATE" value={form.move_in_date} set={v=>set('move_in_date',v)}/><Field label="TOTAL OCCUPANTS" value={form.occupants} set={v=>set('occupants',v)} keyboard="numeric"/><Field label="PETS" value={form.pets} set={v=>set('pets',v)} placeholder="None, or describe pets"/></>:null}
{step===4?<><H title="Housing history"/><Field label="CURRENT / PRIOR HOUSING" value={form.housing_history} set={v=>set('housing_history',v)} multiline/><Field label="LANDLORD / HOUSING REFERENCES" value={form.references} set={v=>set('references',v)} multiline/><Field label="ADDITIONAL NOTES" value={form.additional_notes} set={v=>set('additional_notes',v)} multiline/></>:null}
{step===5?<><H title="Review & submit"/><Review label="APPLICANT" value={[form.first_name,form.last_name].filter(Boolean).join(' ')}/><Review label="CONTACT" value={[form.email,form.phone].filter(Boolean).join(' · ')}/><Review label="CURRENT ADDRESS" value={form.current_address}/><Review label="EMPLOYMENT" value={[form.employment_status,form.employer].filter(Boolean).join(' · ')}/><Review label="MONTHLY INCOME" value={form.monthly_income?('$'+form.monthly_income):''}/><Review label="MOVE-IN" value={form.move_in_date}/><Review label="OCCUPANTS" value={form.occupants}/><Review label="PETS" value={form.pets}/><Review label="HOUSING HISTORY" value={form.housing_history}/><View style={s.notice}><Text style={s.noticeTitle}>BEFORE YOU SUBMIT</Text><Text style={s.noticeBody}>Confirm these answers are accurate. FairPath does not guarantee landlord approval. Screening, verification, fees and property-specific requirements may still apply.</Text></View></>:null}
<Pressable style={s.primary} disabled={saving} onPress={step===5?submit:next}><Text style={s.primaryText}>{saving?'SAVING…':step===5?'CONFIRM & SUBMIT APPLICATION':'SAVE & CONTINUE →'}</Text></Pressable>{step>1?<Pressable style={s.secondary} onPress={()=>setStep(step-1)}><Text style={s.secondaryText}>← PREVIOUS STEP</Text></Pressable>:null}</ScrollView></ScreenFrame>}
function H({title}:{title:string}){return <><Text style={s.kicker}>STEP DETAILS</Text><Text style={s.heading}>{title}</Text></>}
function Field({label,value,set,placeholder='',keyboard='default',multiline=false}:{label:string;value:string;set:(v:string)=>void;placeholder?:string;keyboard?:any;multiline?:boolean}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={[s.input,multiline&&s.multi]} value={value} onChangeText={set} placeholder={placeholder||'Enter '+label.toLowerCase()} placeholderTextColor={C.muted} keyboardType={keyboard} multiline={multiline}/></View>}
function Review({label,value}:{label:string;value:string}){return <View style={s.review}><Text style={s.label}>{label}</Text><Text style={s.reviewValue}>{value||'Not provided'}</Text></View>}
const s=StyleSheet.create({loading:{color:C.mutedStrong,padding:L.mobileGutter},progress:{flexDirection:'row',gap:5,paddingHorizontal:L.mobileGutter,paddingTop:14},piece:{flex:1,minWidth:0},bar:{height:3,backgroundColor:C.borderStrong},barOn:{backgroundColor:C.lime},step:{color:C.muted,fontFamily:F.extraBold,fontSize:5.5,letterSpacing:.4,marginTop:5},stepOn:{color:C.lime},content:{padding:L.mobileGutter,paddingBottom:40},fast:{borderWidth:1,borderColor:'#526F2B',padding:12,marginBottom:18},fastText:{color:C.mutedStrong,fontSize:9,lineHeight:14,marginTop:7},kicker:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1.1},heading:{color:C.white,fontFamily:F.black,fontSize:26,marginTop:5,marginBottom:16},field:{marginBottom:13},label:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:7,letterSpacing:.8,marginBottom:6},input:{minHeight:48,borderWidth:1,borderColor:C.borderStrong,color:C.white,paddingHorizontal:12,fontSize:13},multi:{minHeight:92,paddingTop:12,textAlignVertical:'top'},primary:{minHeight:50,backgroundColor:C.lime,alignItems:'center',justifyContent:'center',marginTop:12},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:8.5,letterSpacing:.8},secondary:{minHeight:44,borderWidth:1,borderColor:C.borderStrong,alignItems:'center',justifyContent:'center',marginTop:8},secondaryText:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:8},review:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:C.border},reviewValue:{color:C.white,fontSize:12,lineHeight:18},notice:{borderWidth:1,borderColor:'#526F2B',padding:14,marginTop:18},noticeTitle:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1},noticeBody:{color:C.mutedStrong,fontSize:10,lineHeight:16,marginTop:6}});