import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Lucide } from '@react-native-vector-icons/lucide';
import { ScreenFrame, PageHeader } from '@/components/ProductChrome';
import { FairPathColors as C, FairPathFonts as F, FairPathLayout as L } from '@/constants/fairpath';
import { createHousingReport } from '@/core/opportunities/opportunity-service';
const REASONS=[['incorrect_info','Incorrect listing info'],['suspected_scam','Suspected scam'],['unavailable','Home is unavailable'],['discrimination_concern','Discrimination concern'],['safety_concern','Safety concern'],['other','Other']] as const;
export default function HousingReport(){const {id}=useLocalSearchParams<{id:string}>();const [reason,setReason]=useState<(typeof REASONS)[number][0]|null>(null);const [details,setDetails]=useState('');const [saving,setSaving]=useState(false);
 async function submit(){if(!id||saving)return;if(!reason){Alert.alert('Choose a reason','Select why you are reporting this listing.');return}setSaving(true);try{await createHousingReport({listingId:id,reason,details});Alert.alert('Report received','FairPath saved your report for review. Thank you for helping keep listings accurate and safe.');router.back()}catch(e){if(e instanceof Error&&e.message==='SIGNED_OUT'){router.push(('/sign-up?returnTo='+encodeURIComponent('/housing-report/'+id)) as never);return}Alert.alert('Could not send report','Please try again.')}finally{setSaving(false)}}
 return <ScreenFrame><PageHeader eyebrow="FAIRPATH SAFETY" title="Report listing" backTo={id?'/housing/'+id:'/find-housing'}/><ScrollView contentContainerStyle={s.content}><Text style={s.intro}>Reports help FairPath review inaccurate, unsafe, discriminatory, or suspicious listings. Reporting does not automatically remove a listing.</Text><Text style={s.label}>REASON</Text><View style={s.grid}>{REASONS.map(([value,label])=><Pressable key={value} style={[s.choice,reason===value&&s.choiceOn]} onPress={()=>setReason(value)}><Text style={[s.choiceText,reason===value&&s.choiceTextOn]}>{label.toUpperCase()}</Text></Pressable>)}</View><Text style={s.label}>DETAILS</Text><TextInput style={[s.input,s.multi]} value={details} onChangeText={setDetails} multiline placeholder="Tell FairPath what happened or what looks wrong." placeholderTextColor={C.muted}/><Pressable style={s.primary} onPress={()=>void submit()} disabled={saving}><Text style={s.primaryText}>{saving?'SENDING…':'SUBMIT REPORT'}</Text><Lucide name="shield-alert" color={C.black} size={15}/></Pressable></ScrollView></ScreenFrame>}
const s=StyleSheet.create({content:{padding:L.mobileGutter,paddingBottom:40},intro:{color:C.mutedStrong,fontSize:11,lineHeight:17,marginBottom:18},label:{color:C.lime,fontFamily:F.extraBold,fontSize:8,letterSpacing:1,marginTop:12,marginBottom:7},grid:{gap:8},choice:{minHeight:43,borderWidth:1,borderColor:C.borderStrong,justifyContent:'center',paddingHorizontal:12},choiceOn:{borderColor:C.lime,backgroundColor:'#10150C'},choiceText:{color:C.mutedStrong,fontFamily:F.extraBold,fontSize:8},choiceTextOn:{color:C.lime},input:{minHeight:48,borderWidth:1,borderColor:C.borderStrong,color:C.white,paddingHorizontal:12,fontSize:13},multi:{minHeight:120,paddingTop:12,textAlignVertical:'top'},primary:{height:50,backgroundColor:C.lime,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:14,marginTop:18},primaryText:{color:C.black,fontFamily:F.extraBold,fontSize:9,letterSpacing:.8}});
